### ISSUE TITLE
Use USB DAC with Raspotify?

### ISSUE THREAD

**Issue by grolin77** [dtcooper/raspotify#10]
Hi!

Thank you for a nice project! :-)

Can a universal USB DAC be used instead of the internal DAC that outputs the analog signal through the 3.5 mm audio jack on the Raspberry Pi 3? I do not want to use the internal DAC or a HiFi Berry.
If so, do I have to change/add anything in the /etc/default/raspotify config file to get this to work?
I have not tried this yet since I want to know that it will work before I buy a USB DAC. :-)

**Comment by dtcooper** [comment]
Yes. I use a Griffin iMic with no problems. Follow the instructions in the Readme, and if you have any issues get in touch. Thanks.
