### ISSUE TITLE
Keep up to date with "unattended-upgrades"

### ISSUE THREAD

**Issue by kwinz** [dtcooper/raspotify#101]
I am using APT "unattended-upgrades" to keep my RPi updated.
My `/etc/apt/apt.conf.d/50unattended-upgrades` contains:
```
"origin=Raspbian,codename=${distro_codename},label=Raspbian";
"origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation";
```
This works and all packages get updated - _except for raspotify_.
How can I add raspotify to be updated?

**Comment by jellemdekker** [comment]
You would need to add another line to the file with the specific information of the Raspotify repository. Instructions for doing this are [here](https://askubuntu.com/a/87854). Please update this issue with the appropriate solution so others can take advantage of this as well. :)
