### ISSUE TITLE
Huge delays before playing

### ISSUE THREAD

**Issue by totomaze** [dtcooper/raspotify#103]
Hi,
When I start a song through raspotify the sound will come only after the song is loaded.(log)
This result in huge delay before the song start playing from 30s to 1min after.

Thanks

**Comment by neiljohari** [comment]
I am currently experiencing this too on a Raspberry Pi 3. I've tried playing with the cache and bitrate quality so far—no luck.

**Comment by audifaxdev** [comment]
The delays varies, The song is displayed as playing for 5 to 30 seconds before I can hear the beginning of the song.

**Comment by totomaze** [comment]
Update :
After my download speed came back up the delays are down to 3-10s.
I ended up using media server (windows) with the spotify app.
Thats a shame we can't run open.spotify.com on a rasberryPi
ps: I am a premium user

**Comment by neiljohari** [comment]
@audifaxdev I have a premium account, still experience delays. Going to see if a new router makes any difference soon as the old one had some problems and was severely hurting our speeds.

**Comment by 8pointagenda** [comment]
Has anybody found a solution to this issue yet?

**Comment by redcrayonn** [comment]
Issue happens continuosly for me.

**Comment by charlesmillet** [comment]
I also have between 5 and 10 seconds of delay on my Pi 3 and no delay on my desktop.

**Comment by thebeater** [comment]
Same here, i have an delay of minimum 8 seconds after my app is showing the playback signal.

**Comment by rulingspear** [comment]
Me too. Running on a raspi 1 B+. No network issues as far as I'm concerned, other wifi enabled spotify players are instantly playing.

**Comment by charlesmillet** [comment]
The delay has disappear since my internet speed has increased (I had 2MBits and now 1000).

**Comment by luke-herm** [comment]
found a cheap workaround for me... playing a long, empty mp3 while raspotify is running gave me continuous playback somehow
