### ISSUE TITLE
Replay stops after a few songs

### ISSUE THREAD

**Issue by andy646362** [dtcooper/raspotify#109]
edit
This seems to have been resolved entirely. In fact, establishing
the connection between Spotify on Notebook and Raspotify is 
now vastly better than it has ever been before. No clue as to why
that might be though. 
/edit

Hi there,

recently I've had a few issues with raspotify just randomly stopping 
the playback after a few songs. It still seems to play the song to the end, but
without audio and after the song ends, I lose connection.
Log below:

`### May 10 14:09:05 osmc librespot[1913]:   10:   0x57485f - librespot_playback::player::PlayerInternal::run::h296c59bd7682ffbf
May 10 14:09:05 osmc librespot[1913]:   11:   0x4f44bb - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ef34e9728d818f7
May 10 14:09:05 osmc librespot[1913]:   12:   0x507a03 - std::panicking::try::do_call::h55970923d54b3006
May 10 14:09:05 osmc librespot[1913]:   13:   0x9dc673 - __rust_maybe_catch_panic
May 10 14:09:06 osmc librespot[1913]:                        at libpanic_unwind/lib.rs:102
May 10 14:09:06 osmc librespot[1913]:   14:   0x50992b - <F as alloc::boxed::FnBox<A>>::call_box::h6c97a59281f0cee4
May 10 14:09:06 osmc librespot[1913]:   15:   0x9d32df - std::sys::unix::thread::Thread::new::thread_start::hb1d1727b173caaf8
May 10 14:09:06 osmc librespot[1913]:                        at /checkout/src/liballoc/boxed.rs:798
May 10 14:09:06 osmc librespot[1913]:                        at libstd/sys_common/thread.rs:24
May 10 14:09:06 osmc librespot[1913]:                        at libstd/sys/unix/thread.rs:90
~
`

After the song ends and connection is lost:

`May 10 14:13:57 osmc systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
May 10 14:13:57 osmc systemd[1]: raspotify.service: Unit entered failed state.
May 10 14:13:57 osmc systemd[1]: raspotify.service: Failed with result 'exit-code'.
`

Thanks for any help in advance.

**Comment by rodet** [comment]
Did you maybe run out of disk space? https://github.com/dtcooper/raspotify/issues/112#issuecomment-393490373
