### ISSUE TITLE
How to make it work on ODROID C2

### ISSUE THREAD

**Issue by ezekini** [dtcooper/raspotify#11]
Hello, is there a way to make it work on an ODROID C2 device? The curl install line returns "Raspotify installer only runs on a Raspberry Pi". 
Thank you

**Comment by daniellhotka** [comment]
As mentioned on the front page, this is a wrapper for [librespot](https://github.com/plietar/librespot) to be used on Raspberry Pi. I assume you could install it manually on an ODROID C2 from that source

**Comment by JasonLG1979** [comment]
Closing because of age and inactivity. A new version of Raspotify based on a much newer version librespot will be released soon. When that happens please update and if the issue persists reopen the issue.
