### ISSUE TITLE
Not an Issue but Thanking

### ISSUE THREAD

**Issue by e-3-s** [dtcooper/raspotify#110]
Sorry that I made a issue but I just wanted to thank you guys for your hard work.
This is so awesome.
After 4 hours getting my audio output right on the raspberry pi and after rebooting
it finaly worked.

Like a charm!
My friends can connect to it with their spotify software on their laptop and play music.
So awesome
Thanks for this. keep updating it. awesome package

**Comment by dimitrisTim** [comment]
Agree. It is awesome! I connected from my phone once, and can listen to music all day from the raspberrypi. Huge thanks and props to the team :+1:

**Comment by dtcooper** [comment]
Thanks @e-3-s and @dimitrisTim! :)
