### ISSUE TITLE
How can this work?

### ISSUE THREAD

**Issue by zilexa** [dtcooper/raspotify#12]
I thought it was no longer possible to obtain a Spotify key, required to use libspotify. I never properly saved my key so now I don't have Spotify Connect on my raspberry anymore :(

Your solution seems so simple, does it rely on the new (beta) web API from Spotify?

**Comment by daniellhotka** [comment]
It doesn't use libspotify. As mentioned in the front page documentation, it uses [librespot](https://github.com/plietar/librespot), which doesn't need a key
