### ISSUE TITLE
Main panics on start

### ISSUE THREAD

**Issue by okrantz** [dtcooper/raspotify#120]
Since a few days I'm having this trouble with raspotify - it dies for some reason.

May 31 10:40:05 osmc-Ichabod systemd[1]: Starting Raspotify...
May 31 10:40:05 osmc-Ichabod systemd[1]: Started Raspotify.
May 31 10:40:05 osmc-Ichabod librespot[3228]: INFO:librespot: librespot (raspotify) 5f21c25 (2018-01-28). Built on 2018-01-29. Build ID: ol042t2I
May 31 10:40:05 osmc-Ichabod librespot[3228]: DEBUG:librespot: Volume "32768" !
May 31 10:40:05 osmc-Ichabod librespot[3228]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
May 31 10:40:05 osmc-Ichabod librespot[3228]: INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-pp5r.ap.spotify.com:4070"
May 31 10:40:05 osmc-Ichabod librespot[3228]: INFO:librespot_core::session: Authenticated as "XXXXXX" !
May 31 10:40:05 osmc-Ichabod librespot[3228]: DEBUG:librespot_core::session: new Session[0]
May 31 10:40:05 osmc-Ichabod librespot[3228]: DEBUG:librespot::spirc: new Spirc[0]
May 31 10:40:05 osmc-Ichabod librespot[3228]: DEBUG:librespot_core::mercury: new MercuryManager
May 31 10:40:05 osmc-Ichabod librespot[3228]: DEBUG:librespot::player: new Player[0]
May 31 10:40:05 osmc-Ichabod librespot[3228]: INFO:librespot::audio_backend::alsa: Using alsa sink
May 31 10:40:05 osmc-Ichabod librespot[3228]: DEBUG:librespot_core::session: Session[0] strong=3 weak=2
May 31 10:40:05 osmc-Ichabod librespot[3228]: INFO:librespot_core::session: Country: "SE"
May 31 10:40:06 osmc-Ichabod librespot[3228]: DEBUG:librespot_core::mercury: subscribed uri=hm://remote/3/user/XXXXX/ count=0
**May 31 10:40:06 osmc-Ichabod librespot[3228]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:906:4**
May 31 10:40:06 osmc-Ichabod librespot[3228]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
May 31 10:40:06 osmc-Ichabod librespot[3228]: DEBUG:librespot::spirc: drop Spirc[0]
May 31 10:40:06 osmc-Ichabod librespot[3228]: DEBUG:librespot::player: Shutting down player thread ...
May 31 10:40:06 osmc-Ichabod librespot[3228]: DEBUG:librespot::player: drop Player[0]
May 31 10:40:06 osmc-Ichabod librespot[3228]: DEBUG:librespot_core::session: drop Session[0]
May 31 10:40:06 osmc-Ichabod librespot[3228]: DEBUG:librespot_core::mercury: drop MercuryManager
May 31 10:40:06 osmc-Ichabod librespot[3228]: DEBUG:librespot_core::session: drop Dispatch
May 31 10:40:06 osmc-Ichabod systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
May 31 10:40:06 osmc-Ichabod systemd[1]: raspotify.service: Unit entered failed state.
May 31 10:40:06 osmc-Ichabod systemd[1]: raspotify.service: Failed with result 'exit-code'.

uname -a
Linux osmc-Ichabod 3.14.29-93-osmc #1 SMP Sat Apr 28 18:58:06 UTC 2018 aarch64 GNU/Linux

I've updated to latest release. 

Any ideas?

Otherwise - great work!

okrantz

**Comment by dtcooper** [comment]
Based on the logs, you're _not_ on the latest release. Please update!
