### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))', /checkout/src/libcore/result.rs:916:5

### ISSUE THREAD

**Issue by ramonhollands** [dtcooper/raspotify#122]
Raspotify is mostly not working anymore. Sometimes, it does after restarting a lot. What is above error message saying? No internet connection?

Thanks and regards,
Ramon

**Comment by ramonhollands** [comment]
Yes, indeed it is solved in the last version. I though I was using the last
version, but I was not. Sorry for bothering.

Regards,
Ramon

On 3 June 2018 at 14:23:56, l3d00m (notifications@github.com) wrote:

This already fixed and I think the newest raspotify should include the fix,
which version are you using?

Fixed here: librespot-org/librespot#224
<https://github.com/librespot-org/librespot/pull/224>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dtcooper/raspotify/issues/122#issuecomment-394158701>,
or mute the thread

**Comment by jellemdekker** [comment]
Please close this issue if your problem was solved. Thank you!
