### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SpotifyIdError', libcore/result.rs:945:5

### ISSUE THREAD

**Issue by mcflo81** [dtcooper/raspotify#123]
Hi there, 

first of all: thanks for your good work! I am a raspberry / linux / raspotify beginner, so the second thing is asking for your patience.

Coming to the point: I updated to the latest version as I had connection issues. It works on one smartphone, but on the other I do find the error above. What can I do?

Thanks!
Florian

**Comment by jellemdekker** [comment]
This has been fixed in the latest version of Raspotify. Please have a look at issue #122. If your problem is solved, please consider closing this issue yourself with the button below.

**Comment by mcflo81** [comment]
Thanks!
