### ISSUE TITLE
RPi doesn't show up in Spotify Connect

### ISSUE THREAD

**Issue by Riyge** [dtcooper/raspotify#125]
I installed raspotify yesterday, and it worked like a charm. Changed the bitrate to 320, entered my login information and set a name for the device. When I woke up a few hours ago I couldn't find the device anymore. Not on my pc, not on my phone. I rebooted the RPi, but this didn't fix the issue. I also deleted & installed raspotify again, but this also did not work.

Edit: Found the issue. I connected my pc and phone to another network, I'm stupid.
This issue can be closed

**Comment by jellemdekker** [comment]
Please close this issue yourself with the button below to reduce the clutter in the list of issues. Thank you!
