### ISSUE TITLE
[RPi3] slower song speed

### ISSUE THREAD

**Issue by zamszowy** [dtcooper/raspotify#129]
Hi,

I've noticed that song played on Raspberry Pi 3 (with OSMC 2018.06-1 installed) has significantly slower speed than played on other platforms (phone, desktop computer).
You can hear the difference in the two recordings (MP3 format) that I've made: [slow-speed.zip](https://github.com/dtcooper/raspotify/files/2173652/slow-speed.zip)

Does anyone know how to fix this?

**Comment by zamszowy** [comment]
Seems that this is related to OSMC itself, as I've just installed raspbian and the issue does not exist there (also the quality is better).

**Comment by steinhmor** [comment]
I'm having similar problems with raspotify on dietpi. Maybe it's not OSMC related?

**Comment by zamszowy** [comment]
> @zamszowy can you please reopen this issue?

Done.
