### ISSUE TITLE
Install as a headless client

### ISSUE THREAD

**Issue by tanoielis** [dtcooper/raspotify#136]
I'd like to request a headless installer that starts the client on boot/reboot for use in the car.

**Comment by 5AMsan** [comment]
According to my experience with Rapsotify, all you have to do to enable auto start is:
```
$: systemctl raspotify enable
```

**Comment by vguttmann** [comment]
If I'm not mistaken, this is also taken care of in the current version. if this resolved your issue, please mark the issue as solved @tanoielis
