### ISSUE TITLE
HDMI output

### ISSUE THREAD

**Issue by gcorwin** [dtcooper/raspotify#137]
Just wanted to make note that you shouldn't need to force the device to play over HDMI in the Raspotify config file. 

If you modify /boot/config.txt and uncomment the line hdmi_drive = 2 then the audio should automatically play over HDMI. At least that is what did it for me.  

Thanks for your work on this, great stuff!

**Comment by 110101011** [comment]
U could also use raspi-config for this, it's been developed to change this kind of settings.

**Comment by dtcooper** [comment]
No progress or response to @110101011's suggestion. Closing.
