### ISSUE TITLE
Trigger music start/stop

### ISSUE THREAD

**Issue by adrianknorr** [dtcooper/raspotify#140]
Hey,

i am trying to automate my house.
One neat thing is this application to play the music via the RasPi. But, to save energy, my speakers are connected to a smart plug and need to be turned on. 
Now my question:
Is there a way, that raspotify triggers the Home Assistant application (or similar) which then turns my speaker on or off?
One thing i already tried was the audio driver. It writes in a textfile, if there's audio or not. But then i had to run a script every minute to check this file, which isn't the optimum.

Thank you very much in advance!
Greetings from Germany.

**Comment by dtcooper** [comment]
Try using liquidsoap?
