### ISSUE TITLE
Remote Playback appears just for my account ?

### ISSUE THREAD

**Issue by ivanrodrigues0** [dtcooper/raspotify#148]
Hi guys

I'm trying found a way to set up to Remote Playback appears just for my account, now appears for anyone premium account on my network.

Anyone already had this question ?

Thx
Ivan

**Comment by e-3-s** [comment]
I am also very interested in this. 
Is there a way to have next, previous, pause and play functions or commands?

**Comment by 110101011** [comment]
As raspotify needs account information it would be tied to that account, then only possibility I can see is using multiple instances with different account credentials, and edit the alsa config to let all instances have access to the soundcard
