### ISSUE TITLE
ConnectionReset after one title

### ISSUE THREAD

**Issue by dandud100** [dtcooper/raspotify#149]
Sep 24 17:30:31 raspberrypi librespot[782]: ERROR:librespot_core::session: Os { code: 104, kind: ConnectionReset, message: "Connection reset~

If i just let music play over raspotify, and minimize the spotify app, it just play the actual song to the end and get an ConnectionReset.

**Comment by Uglendertog** [comment]
I have the same problem and gets the same error code

. As soon as i minimize the spotify app on my telephone it just plays the song to the end.

**Comment by Hammit** [comment]
I too have this issue. I'm using the Ubuntu Linux Spotify Client, not mobile though. Happens after a few songs. Happens when using Android mobile client too.

    Dec 21 10:34:20 music librespot[506]: ERROR:librespot_core::session: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }

**Comment by lamoe02** [comment]
same here unfortunately... :(

**Comment by sfai05** [comment]
Got this issue after I update the config of BITRATE to 320
Comment out the config then all works as normal
