### ISSUE TITLE
Volume pumping

### ISSUE THREAD

**Issue by microfx** [dtcooper/raspotify#151]
Hey!

Only when listening over Spotify connect with the Pi I get pumping volume - like a bad compressor setting or something. This is really irritating. Anything I could try? 

Cheers!

**Comment by qbovv** [comment]
This is my setup:
uncomment OPTIONS in etc/default/raspotify, fill in or delete your credentials at wish and add --normalisation-pregain=0

OPTIONS="--username ********@******.*** --password **** --normalisation-pregain=0"

uncomment VOLUME_ARGS 

VOLUME_ARGS="--enable-volume-normalisation --linear-volume --initial-volume=50"
then try increasing the volume on your app and listen what it does.

**Comment by qbovv** [comment]
After long listening and switching between audio-normalization and no normalization, there's no doubt, audio-normalization always sounds worse, high RMS-tracks or low RMS tracks. 
So I take the inconvenience of listening 'pure' (no norm) with alternating loud and soft songs, so I have the full dynamic.
