### ISSUE TITLE
Unclear on how to disable volume normalisation

### ISSUE THREAD

**Issue by ja14000** [dtcooper/raspotify#152]
I am unclear on how to disable the volume normalisation feature without affecting any other of the default settings. 

From what I understand volume normalisation is enabled by default and you must change some arguments to disable it. 

When looking at all of the arguments available there is one available to enable audio normalisation but there doesn't seem to be an argument to disable it.

What I have done is uncommented the VOLUME-ARGS line and removed the' --enable-volume-normalisation' flag.

Is this the correct way to disable volume normalisation?

Thanks

**Comment by 110101011** [comment]
Looking at librespot remove that line of code should be sufficient to disable volume normalisation

**Comment by ja14000** [comment]
Thanks for the response, glad to have confirmation. Please could you point me at the librespot documentation? I'd be interested in reading some more about how this works.

Many thanks

**Comment by 110101011** [comment]
Documentation for librespot:

https://github.com/librespot-org/librespot/blob/master/README.md

**Comment by vguttmann** [comment]
If your issue is resolved, you should consider closing it @ja14000
