### ISSUE TITLE
raspotify on ubuntu x86/x64

### ISSUE THREAD

**Issue by untitledlt** [dtcooper/raspotify#155]
Is it possible to run this awesome service on regular Ubuntu server with x86/x64 architecture?

**Comment by dtcooper** [comment]
It is not, however check out [librespot](https://github.com/librespot-org/librespot), which is the underlying daemon.

**Comment by ltotsas** [comment]
Any updates for that matter? @untitledlt ?

**Comment by untitledlt** [comment]
haven't tried
