### ISSUE TITLE
Service not starting (code=exited, status=101) - main panic "stream did not contain valid UTF-8"

### ISSUE THREAD

**Issue by Jerem01480** [dtcooper/raspotify#156]
Hello,

Since a few weeks now (not really sure of when it starts) Raspotify refuses to start.

When checking the status of the service, I get:

> raspotify.service - Raspotify
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2018-10-23 10:30:46 CEST; 3s ago
  Process: 31079 ExecStart=/usr/bin/librespot --name ${DEVICE_NAME} $BACKEND_ARGS --bitrate ${BITRATE} $CACHE_ARGS $VOLUME_ARGS (code=exited, status=101)
  Process: 31076 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 31073 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
 Main PID: 31079 (code=exited, status=101)
oct. 23 10:30:46 Toto systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
oct. 23 10:30:46 Toto systemd[1]: raspotify.service: Unit entered failed state.
oct. 23 10:30:46 Toto systemd[1]: raspotify.service: Failed with result 'exit-code'.

And in journalctl I have:

> oct. 23 10:30:46 Toto systemd[1]: Starting Raspotify...
oct. 23 10:30:46 Toto systemd[1]: Started Raspotify.
oct. 23 10:30:46 Toto librespot[31079]: INFO:librespot: librespot (raspotify v0.11.5) 3614404 (2018-10-16). Built on 2018-10-17. Build ID: UD3TRyOa
oct. 23 10:30:46 Toto librespot[31079]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', libcore/result.rs:945:5
oct. 23 10:30:46 Toto librespot[31079]: stack backtrace:
oct. 23 10:30:46 Toto librespot[31079]:    0:   0x94c72b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hcf3dddc6200fad89
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
oct. 23 10:30:46 Toto librespot[31079]:    1:   0x93ae3f - std::sys_common::backtrace::print::ha74183f8146bff60
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/sys_common/backtrace.rs:71
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/sys_common/backtrace.rs:59
oct. 23 10:30:46 Toto librespot[31079]:    2:   0x938957 - std::panicking::default_hook::{{closure}}::h8790cb9f07a765c6
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panicking.rs:211
oct. 23 10:30:46 Toto librespot[31079]:    3:   0x9385d7 - std::panicking::default_hook::h8932bf45ef21858c
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panicking.rs:227
oct. 23 10:30:46 Toto librespot[31079]:    4:   0x93907f - std::panicking::rust_panic_with_hook::hc91e5f2c01fc689c
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panicking.rs:475
oct. 23 10:30:46 Toto librespot[31079]:    5:   0x938c43 - std::panicking::continue_panic_fmt::h4a8945dc115e38fc
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panicking.rs:390
oct. 23 10:30:46 Toto librespot[31079]:    6:   0x938b2b - rust_begin_unwind
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panicking.rs:325
oct. 23 10:30:46 Toto librespot[31079]:    7:   0x99d02f - core::panicking::panic_fmt::h26b7cf0675909ac6
oct. 23 10:30:46 Toto librespot[31079]:                        at libcore/panicking.rs:77
oct. 23 10:30:46 Toto librespot[31079]:    8:   0x623d6b - core::result::unwrap_failed::h729913a17cbc9915
oct. 23 10:30:46 Toto librespot[31079]:    9:   0x5b0a0b - librespot_core::authentication::Credentials::from_file::hb3665dd9211cbeb3
oct. 23 10:30:46 Toto librespot[31079]:   10:   0x64081b - librespot_core::cache::Cache::credentials::h895bc442208774d7
oct. 23 10:30:46 Toto librespot[31079]:   11:   0x4d953b - librespot::main::h7263f0722bde5bef
oct. 23 10:30:46 Toto librespot[31079]:   12:   0x4bf597 - std::rt::lang_start::{{closure}}::hda8c349478babf2e
oct. 23 10:30:46 Toto librespot[31079]:   13:   0x938aa3 - std::panicking::try::do_call::hc221fc47d38c79d7
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/rt.rs:59
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panicking.rs:310
oct. 23 10:30:46 Toto librespot[31079]:   14:   0x958c8f - __rust_maybe_catch_panic
oct. 23 10:30:46 Toto librespot[31079]:                        at libpanic_unwind/lib.rs:105
oct. 23 10:30:46 Toto librespot[31079]:   15:   0x935d5b - std::rt::lang_start_internal::h8c7a5dbe81fee471
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panicking.rs:289
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/panic.rs:392
oct. 23 10:30:46 Toto librespot[31079]:                        at libstd/rt.rs:58
oct. 23 10:30:46 Toto librespot[31079]:   16:   0x4db083 - main
oct. 23 10:30:46 Toto librespot[31079]:   17: 0x76cc6677 - __libc_start_main
oct. 23 10:30:46 Toto systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
oct. 23 10:30:46 Toto systemd[1]: raspotify.service: Unit entered failed state.
oct. 23 10:30:46 Toto systemd[1]: raspotify.service: Failed with result 'exit-code'.

I cannot figure where I can find non valid UTF-8 datas.
 
For information, the system is set in UTF-8 since the beginning and Raspotify was working like a charm before.

Thanks for your help

**Comment by duncan-qabana** [comment]
Since today, I am getting exactly the same error. Tried rebooting and everything, but nothing seems to work!
