### ISSUE TITLE
Raspotify working via LAN, but not via Wifi

### ISSUE THREAD

**Issue by patti9000** [dtcooper/raspotify#157]
Hi,
I'm using a Raspberry 2 with the latest stretch lite image and a edimax dongle.

Everthing is set up and works if I use a LAN cable, but if I use the connection with the wifi dongle, I can't see the Raspotify anymore. I still can ping it and I still can use SSH.

Any ideas?

Thanks
Patti

**Comment by Taskkill** [comment]
I too am in same position.
