### ISSUE TITLE
Shuffle and Repeat are Reset when Selecting a new Song

### ISSUE THREAD

**Issue by ndbeals** [dtcooper/raspotify#159]
Hello!

Thanks for taking the time to read this, as the title states, whenever I'm playing a playlist with shuffle turned on, if I select a new song, it turns off shuffle.

This didn't used to be how it behaved, and I'm wondering how do I get it back?

If there's any more information I can provide, I'd be pleased to.

Thanks,

**Comment by celeryclub** [comment]
This appears to be an issue in librespot as well - https://github.com/librespot-org/librespot/issues/266.

**Comment by ndbeals** [comment]
Yeah @celeryclub , an issue opened by me because this issue sat unanswered for 19 days, I still don't know who exactly the culprit is.

**Comment by celeryclub** [comment]
FWIW I can confirm it's a bug in librespot because I'm running it directly without raspotify and I'm seeing the same behavior you described.

**Comment by ndbeals** [comment]
Since this issue does affect Raspotify users (via librespot that is), did you want me to leave this issue open until upstream resolves it?

**Comment by celeryclub** [comment]
I don't have a strong opinion on the matter. I suppose we could leave it open, then whenever the issue is resolved upstream this one could be closed after librespot is updated here.

**Comment by faabmaster** [comment]
I'm also affected by this issue. Has anyone found a solution to this, considering it's been a year since it was first reported?

**Comment by willstott101** [comment]
Pinging raspotify users about https://github.com/librespot-org/librespot/pull/386 please have a go at using that branch to see if the behaviour is exactly as you expect.
