### ISSUE TITLE
Playing a song via terminal command

### ISSUE THREAD

**Issue by kurcab** [dtcooper/raspotify#162]
Does anyone know how I can start a song/playlist from a bash command so that I could schedule stuff with cron?

**Comment by derWeihnachtsmann** [comment]
I'm unsure at this but maybe you are searching for something like spotipy ?

**Comment by 3579km** [comment]
try aplay but not shure how it will be useful

**Comment by janekszynal** [comment]
hi @kurcab,

I'm building an alarm clock to wake me up with a song from raspotify and ran into this issue as well (if you're looking to schedule stuff with cron, kind of sounds like your project might be similar).

The bash command would then look something like this:

```curl -X "PUT" "https://api.spotify.com/v1/me/player/play" --data "{\"context_uri\":\"spotify:album:5uiLjgmdPV4dgamvmC64Oq\",\"offset\":{\"position\":5},\"position_ms\":0}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQDE3bveuC5-0dFy93uvqMGsM5nkwWlhNQbudi7TtjquB58E_cSedGHwYnG7L5Oc76Yvfh11rFrh9eZ5Ln3Y0Otu4VUdRHjU6AjfVoAPIHiv4lBhahVqdz5r1ZZb0e2DDpShAcT0fnAnYeBvhYm1HsUI0Gw_PWaMfCyWiL9S3SA"```


where `spotify:album:5uiLjgmdPV4dgamvmC64Oq` links to the album you want to play (can also play a track with a slightly different syntax) 
and `BQDE3bveuC5(...)` is an Oauth authorisation token you will have to generate from Spotify.

You should start here:
https://developer.spotify.com/documentation/web-api/quick-start/

Let me know if you need any help!

**Comment by hiyazakite** [comment]
You can use Spotipy (https://github.com/plamere/spotipy) and create a python script that does this.
