### ISSUE TITLE
Librespot unwrap() Error

### ISSUE THREAD

**Issue by crzdg** [dtcooper/raspotify#164]
Raspotify returned to working normally. But couldn't find the problem. Maybe an issue at the Spotify AP i was using. I will leave the issue open as it may give a hint to a bug. Feel free to close it!

Is this already known:

Dec  1 11:18:30 pummeluff librespot[381]: INFO:librespot_playback::player: Loading track "Time of Our Lives - Club Mix" with Spotify URI "spotify:track:34TQDDndJjxthmV9CI9pQ5"
Dec  1 11:18:30 pummeluff librespot[381]: ERROR:librespot_core::channel: channel error: 2 1
Dec  1 11:18:30 pummeluff librespot[381]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', libcore/result.rs:1009:5
Dec  1 11:18:30 pummeluff librespot[381]: stack backtrace:
Dec  1 11:18:30 pummeluff librespot[381]:    0:   0x94bd07 - std::sys::unix::backtrace::tracing:impunwind_backtrace::h63a67ac893ab31ec
Dec  1 11:18:30 pummeluff librespot[381]:                        at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Dec  1 11:18:30 pummeluff librespot[381]:    1:   0x93ac4b - std::sys_common::backtrace::print::ha8f26509b9ff262c
Dec  1 11:18:30 pummeluff librespot[381]:                        at libstd/sys_common/backtrace.rs:71
Dec  1 11:18:30 pummeluff librespot[381]:                        at libstd/sys_common/backtrace.rs:59
Dec  1 11:18:30 pummeluff librespot[381]:    2:   0x9384c3 - std::panicking::default_hook::{{closure}}::hd7e08be4e57c3548
Dec  1 11:18:31 pummeluff librespot[381]:                        at libstd/panicking.rs:211
Dec  1 11:18:31 pummeluff librespot[381]:    3:   0x938123 - std::panicking::default_hook::h216d888df769ef77
Dec  1 11:18:31 pummeluff librespot[381]:                        at libstd/panicking.rs:227
Dec  1 11:18:31 pummeluff librespot[381]:    4:   0x938beb - std::panicking::rust_panic_with_hook::h7d39a7695d8da98f
Dec  1 11:18:31 pummeluff librespot[381]:                        at libstd/panicking.rs:477
Dec  1 11:18:31 pummeluff librespot[381]:    5:   0x9387af - std::panicking::continue_panic_fmt::ha287897123d4a956
Dec  1 11:18:31 pummeluff librespot[381]:                        at libstd/panicking.rs:391
Dec  1 11:18:31 pummeluff librespot[381]:    6:   0x938697 - rust_begin_unwind
Dec  1 11:18:31 pummeluff librespot[381]:                        at libstd/panicking.rs:326
Dec  1 11:18:31 pummeluff librespot[381]:    7:   0x99cbab - core::panicking::panic_fmt::h2155aa66b67fe83c
Dec  1 11:18:31 pummeluff librespot[381]:                        at libcore/panicking.rs:77
Dec  1 11:18:31 pummeluff librespot[381]:    8:   0x561d37 - core::result::unwrap_failed::h9e64d2014305d04d
Dec  1 11:18:31 pummeluff librespot[381]:    9:   0x55f5db - librespot_playback::player::PlayerInternal::run::he8602276b2d7c4e9
Dec  1 11:18:31 pummeluff librespot[381]:   10:   0x4c5743 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29ea0f501be79b11
Dec  1 11:18:31 pummeluff librespot[381]:   11:   0x4d2e1b - std::panicking::try::do_call::h8195d1482b69cd4d
Dec  1 11:18:31 pummeluff librespot[381]:   12:   0x958f8b - __rust_maybe_catch_panic
Dec  1 11:18:31 pummeluff librespot[381]:                        at libpanic_unwind/lib.rs:103
Dec  1 11:18:31 pummeluff librespot[381]:   13:   0x4c84cf - <F as alloc::boxed::FnBox<A>>::call_box::h93b9ad0eb0410395
Dec  1 11:18:31 pummeluff librespot[381]:   14:   0x9377cb - std::sys_common::thread::start_thread::h41cf1ad8630babd4
Dec  1 11:18:31 pummeluff librespot[381]:                        at liballoc/boxed.rs:656
Dec  1 11:18:31 pummeluff librespot[381]:                        at libstd/sys_common/thread.rs:24
Dec  1 11:18:31 pummeluff librespot[381]:   15:   0x93a5df - std::sys::unix::thread::Thread:ew:thread_start::hbd34cf20156b5b37
Dec  1 11:18:31 pummeluff librespot[381]:                        at libstd/sys/unix/thread.rs:90

Same error on both my raspotify installations.
librespot related I think?

Any ideas or just wait for fix from librespot?

My versions

Dec  1 11:18:50 pummeluff librespot[544]: INFO:librespot: librespot (raspotify v0.11.6) d2cadec (2018-11-19). Built on 2018-11-29. Build ID: Uwq1tCGm

**Comment by 1337sup3rh4x0r** [comment]
known issue in librespot, currently no fix yet.
https://github.com/librespot-org/librespot/issues/183
