### ISSUE TITLE
No sound from HDMI, just jack

### ISSUE THREAD

**Issue by neroxyr** [dtcooper/raspotify#174]
Just discovered this project after reinstalling my OSMC, I want to use it to play music on spotify instead of my Echo Dot. Everything goes great, It plays songs but via the 3,5mm jack and not HDMI. Used the ```

aplay -l command:
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
Subdevices: 7/7
Subdevice #0: subdevice #0
Subdevice #1: subdevice #1
Subdevice #2: subdevice #2
Subdevice #3: subdevice #3
Subdevice #4: subdevice #4
Subdevice #5: subdevice #5
Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
Subdevices: 1/1
Subdevice #0: subdevice #0

Chose the --device hw:0,1 but still nothing. The music stored in the external drive plays via HDMI.

**Comment by dtcooper** [comment]
Hi @neroxyr, can you post your `/etc/default/raspotify` file and `sudo systemctl status raspotify` please. (Redact your username and password.)

**Comment by Gusep** [comment]
I second this question. @dtcooper  did you make anything from the pasted output?

**Comment by Malte77** [comment]
Same here - whatever I try, no sound via HDMI

**Comment by andybrown75** [comment]
+1.... thank you

**Comment by yassineim** [comment]
Hello you all, wouldn't hurt to try to have HDMI plugged on both ends, and your TV/receiver turned on *before* turning on your Rapsberry Pi. That works for me with the default config.

**Comment by Cr4z33** [comment]
@dtcooper I am in the same boat.

I am running Raspotify on a Pi 3 B+ connected by HDMI to a TV.

Everything plays OK through HDMI but Raspotify.

config.txt has been edited to force HDMI output.

Please fix. 🙏

**Comment by yassineim** [comment]
Try a clean install of the latest raspbian

**Comment by Cr4z33** [comment]
@yassineim sorry, but that's no sense mate.

I already wrote that everything else is working fine through the HDMI output. ;)

**Comment by ivanovd** [comment]
+1

**Comment by ivanovd** [comment]
I got it to work.

```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

In my case the HDMI is 1,1 therefore I changed the config OPTIONS to:
OPTIONS="--device hw:1,1"

then I restarted the service
sudo systemctl restart raspotify

and it worked :)

**Comment by vikramaditya91** [comment]
For people visitng this thread, you might also want to try:
`OPTIONS= "--device default"`
in the /etc/default/raspotify

**Comment by michaelfeil** [comment]
@vikramaditya91 Thank you. Additionally I found it helpful to set the default device
For people visiting this thread with a permanently connected audio card on their raspberry, e.g. hifiberry, usb-audio etc. Or always want to play audio over headphone jack, never over hdmi etc.
`
$ aplay -l
card 0: Headphones [..]
card 1: sndrpihifiberry [..]
`

`
#/etc/asound.conf
pcm.!default {
    type hw
    card sndrpihifiberry
}

ctl.!default {
    type hw
    card sndrpihifiberry
}
`

sndrpihifiberry can also be set to 1, otherwise 0/Headphones for using the headphone jack
