### ISSUE TITLE
Switching songs causes Raspotify to break

### ISSUE THREAD

**Issue by Squidman474** [dtcooper/raspotify#176]
Whenever I switch songs quickly (i.e. not waiting for 5-10 seconds after switching each song), raspotify breaks. Music stops playing entirely at first, followed a few seconds later by a horrible distorted pulsing noise. From there, I can't even pull up the terminal on my pi- the entire thing freezes up. Any idea how to fix this? I don't really mind waiting a few seconds to switch a song, but when I forget occasionally, I have to unplug and restart the entire pi.

**Comment by Squidman474** [comment]
I've tried uninstalling raspotify, even reformatting the sd card. No luck.

**Comment by warro** [comment]
Same problem here.

**Comment by Razer0123** [comment]
Same, any help would be appreciated

**Comment by brookshank** [comment]
What version pi are you all running on? What kind of power supply?

**Comment by knarxy** [comment]
Same problem
