### ISSUE TITLE
Need some help building for i386 architecture

### ISSUE THREAD

**Issue by kmbt** [dtcooper/raspotify#177]
I have an HP thin client running an i386 processor (Intel Atom) which i would like to run raspotify on. Could you give me any hints on how to build the package for i386 architecture in a most hassle-free way?

**Comment by dtcooper** [comment]
Go ahead and follow the [librespot instructions](https://github.com/librespot-org/librespot) on how to build on 386.

**Comment by kmbt** [comment]
Thanks for help :)
