### ISSUE TITLE
Problem playing podcasts

### ISSUE THREAD

**Issue by joschahenningsen** [dtcooper/raspotify#179]
Spotify Android and Desktop clients are not able to play Podcasts on raspotify. I get the message "Can't play right now. Sorry! You can't play this content while connected to another device." The same tracks can be played via my Sonos speakers and my Chromecast.
Does anyone else have the same issue?

**Comment by lamoe02** [comment]
I have the same issue. I think this is librespot related... See https://github.com/librespot-org/librespot/issues/90

**Comment by mjkpolo** [comment]
Also same issue!!
