### ISSUE TITLE
Device is connected but no sound on RPi 3B+

### ISSUE THREAD

**Issue by yoomy3** [dtcooper/raspotify#185]
I am trying to play a song on Raspberry Pi 3B+ with HiFiBerry DAC+.

The device seems to be connected as I am able to check its connection on the Spotify Web Player, and verified through https://developer.spotify.com/console/get-users-available-devices/ .

However, no sound is coming out from the speaker. It was definitely working fine last week, but suddenly stopped working.

It is not a hardware problem because I do get clear sound from other sound files and YouTube videos.
I also have correct configured `/etc/default/raspotify` since it was working before, and I have not made any change. 

Is anyone else having the same problem? 
If you had a similar problem, but managed to get it fixed, I would really appreciate it if you could share your solution. 

Thanks!

**Comment by andrewtvuong** [comment]
try command 'pkill pulseaudio'
