### ISSUE TITLE
Can't change playlist 

### ISSUE THREAD

**Issue by microfx** [dtcooper/raspotify#186]
Hey!

Since a few weeks I cannot change playlists. When I do the current song stops / plays from the beginning but it is not switching to the new playlist. To be able to do that I have to unconnect spotify connect, change playlist and connect again. I still can add songs to queue and that works. Is this a known issue? 

Cheers!

**Comment by mkoechler** [comment]
I have the exact same issue. It doesnt matter if I control the raspotify from an Android Phone or Windows PC. Just like microfx the only way to change a song is to disconnect, change the song on the local device and then connect again.

**Comment by microfx** [comment]
iOS 12.1 + macOS here

**Comment by creisey** [comment]
same here...

**Comment by mrpete69** [comment]
Same here. Android and iOS. Raspotify running on a central RPi 3 with three snapcast clients.

**Comment by jimsan72** [comment]
Had the same issue, just updated the Raspberry Pi, worked fine after that.
sudo apt-get update
sudo apt-get dist-upgrade

**Comment by creisey** [comment]
thanks a lot, now everything works as before!

**Comment by krzysiacz** [comment]
Same here. Update cured the problem. Thanks !
