### ISSUE TITLE
Spotify stops playing: Error sending packet OS

### ISSUE THREAD

**Issue by Csierra099** [dtcooper/raspotify#193]
Hey guys! So after using Raspotify for about 3 weeks already I have encountred an issue that has to do with #112, issue that I posted but didnt really know what it was, after seeing what the log said I encounted with a problem that says Error Sending Packet OS, anyone knows what I could be?

pi@MediaCenter:~ $ journalctl --system _SYSTEMD_UNIT=raspotify.service
-- Logs begin at Mon 2019-04-01 12:46:55 EDT, end at Mon 2019-04-01 16:15:42 EDT. --
Apr 01 12:47:08 MediaCenter librespot[435]: INFO:librespot: librespot (raspotify v0.12.0) ef28df6 (2019-03-14). Built on 2019-03-14. Build ID: BFEig1gv
Apr 01 12:47:09 MediaCenter librespot[435]: WARN:<unknown>: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Apr 01 12:47:09 MediaCenter librespot[435]: INFO:librespot_core::session: Connecting to AP "guc3-accesspoint-b-467m.ap.spotify.com:4070"
Apr 01 12:47:09 MediaCenter librespot[435]: INFO:librespot_core::session: Authenticated as "hotelabyt" !
Apr 01 12:47:09 MediaCenter librespot[435]: INFO:librespot_playback::audio_backend::alsa: Using alsa sink
Apr 01 12:47:09 MediaCenter librespot[435]: INFO:librespot_core::session: Country: "MX"
Apr 01 13:00:02 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "The Joke" with Spotify URI "spotify:track:37nD8NJhod8BEZ6EGYo2gT"
Apr 01 13:00:04 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "The Joke" loaded
Apr 01 13:02:20 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Is That Alright?" with Spotify URI "spotify:track:172e82oK9vGoBPvc6SqMm5"
Apr 01 13:02:21 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Is That Alright?" loaded
Apr 01 13:05:32 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Hold Your Head Up High - Recorded at Spotify Studios NYC" with Spotify URI "
Apr 01 13:05:32 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Hold Your Head Up High - Recorded at Spotify Studios NYC" loaded
Apr 01 13:09:06 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "No One's Gonna Love You (Stockholm Version)" with Spotify URI "spotify:track
Apr 01 13:09:06 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "No One's Gonna Love You (Stockholm Version)" loaded
Apr 01 13:12:55 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Sign of the Times" with Spotify URI "spotify:track:5ELRkzdzz0HvGpMDlfZHkV"
Apr 01 13:12:55 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Sign of the Times" loaded
Apr 01 13:18:35 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "If You Ever Wanna Be In Love - James Bay Spotify Session 2015" with Spotify
Apr 01 13:18:35 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "If You Ever Wanna Be In Love - James Bay Spotify Session 2015" loaded
Apr 01 13:22:32 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Lonesome" with Spotify URI "spotify:track:0j3v2MeAl14a7I1F3vvewM"
Apr 01 13:22:32 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Lonesome" loaded
Apr 01 13:26:22 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Waking Up Slow - Piano" with Spotify URI "spotify:track:7E9QA6hL8Ebk0yHXeV1U
Apr 01 13:26:22 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Waking up Slow - Piano Version" loaded
Apr 01 13:30:03 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Remedy" with Spotify URI "spotify:track:7GgQi7JTG4b6J4iEF4RTjF"
Apr 01 13:30:03 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Remedy" loaded
Apr 01 13:34:09 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Don't Let Me Down" with Spotify URI "spotify:track:6oqlWkAUCqBXjvorIRSm54"
Apr 01 13:34:09 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Don't Let Me Down" loaded
Apr 01 13:37:09 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "What A Wonderful World" with Spotify URI "spotify:track:2a2gJ4YinLgIovY75zA0
Apr 01 13:37:09 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "What A Wonderful World" loaded
Apr 01 13:42:02 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "I Get to Love You" with Spotify URI "spotify:track:3CV4lFELdziNM1OnHU8nwz"
Apr 01 13:42:03 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "I Get to Love You" loaded
Apr 01 13:46:02 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "The Best You Had - Acoustic Version" with Spotify URI "spotify:track:1JyMina
Apr 01 13:46:02 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "The Best You Had - Acoustic Version" loaded
**Apr 01 13:46:36 MediaCenter librespot[435]: WARN:<unknown>: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Apr 01 13:46:38 MediaCenter librespot[435]: WARN:<unknown>: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
Apr 01 13:46:45 MediaCenter librespot[435]: WARN:<unknown>: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }**
Apr 01 13:49:20 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Too Good At Goodbyes" with Spotify URI "spotify:track:3VlbOrM6nYPprVvzBZllE5
Apr 01 13:49:20 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Too Good At Goodbyes" loaded
Apr 01 13:52:41 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Make You Feel My Love" with Spotify URI "spotify:track:7rPLZ8Krm6CZIbraFUlnW
Apr 01 13:52:41 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Make You Feel My Love" loaded
Apr 01 13:56:13 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "A Thousand Years" with Spotify URI "spotify:track:6lanRgr6wXibZr8KgzXxBl"
Apr 01 13:56:13 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "A Thousand Years" loaded
Apr 01 14:00:58 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "All On My Mind - Acoustic" with Spotify URI "spotify:track:4piJ8pnoRvC5sqMEp
Apr 01 14:00:58 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "All On My Mind - Acoustic" loaded
Apr 01 14:04:47 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Somewhere Only We Know" with Spotify URI "spotify:track:0ll8uFnc0nANY35E0Lfx
Apr 01 14:04:48 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Somewhere Only We Know" loaded
Apr 01 14:08:44 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Stitches" with Spotify URI "spotify:track:3Jy394MtpM2xciRBTzxBlg"
Apr 01 14:08:44 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Stitches" loaded
Apr 01 14:12:50 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "In a New Bed" with Spotify URI "spotify:track:4Or1Yp4i3VANJE6E39ys91"
Apr 01 14:12:50 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "In a New Bed" loaded
Apr 01 14:16:31 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Helium" with Spotify URI "spotify:track:4S6fv0puLCsfYjyBTPDb9k"
Apr 01 14:16:31 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Helium" loaded
Apr 01 14:20:43 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "The Scientist" with Spotify URI "spotify:track:75JFxkI2RXiU7L9VXzMkle"
Apr 01 14:20:44 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "The Scientist" loaded
Apr 01 14:25:53 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Stone" with Spotify URI "spotify:track:6cRExfWfj87zhACU30aW7l"
Apr 01 14:25:53 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Stone" loaded
Apr 01 14:29:29 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "hate u love u" with Spotify URI "spotify:track:6ATgDc6e4sPn84hvJsAmPt"
Apr 01 14:29:30 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "hate u love u" loaded
Apr 01 14:32:25 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Liability" with Spotify URI "spotify:track:4JyLFq2mHC8JPFTXHwYPWD"
Apr 01 14:32:25 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Liability" loaded
Apr 01 14:35:16 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Like I'm Gonna Lose You" with Spotify URI "spotify:track:2pV8RpdLemcyMWko8dA
Apr 01 14:35:17 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Like I'm Gonna Lose You" loaded
Apr 01 14:39:09 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Not Ready to Say Goodbye" with Spotify URI "spotify:track:37qQafvqJgEou8nZXF
Apr 01 14:39:09 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Not Ready to Say Goodbye" loaded
Apr 01 14:42:59 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Don't Forget About Me" with Spotify URI "spotify:track:4gVZhkcsZcwQ4mU1gEeXE
Apr 01 14:42:59 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Don't Forget About Me" loaded
Apr 01 14:47:27 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Speechless" with Spotify URI "spotify:track:2PjDWdGvvbLQfRRTQIZPmv"
Apr 01 14:47:28 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Speechless" loaded
Apr 01 14:51:58 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "If I Ain't Got You" with Spotify URI "spotify:track:3XVBdLihbNbxUwZosxcGuJ"
Apr 01 14:51:58 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "If I Ain't Got You" loaded
Apr 01 14:55:47 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Elastic Heart - Piano Version" with Spotify URI "spotify:track:0udoMICxzaUbN
Apr 01 14:55:47 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Elastic Heart - Piano Version" loaded
Apr 01 14:55:47 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Lay Me Down" with Spotify URI "spotify:track:6x69yrZAJvsYxhk0CJS4uT"
Apr 01 14:55:48 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Lay Me Down" loaded
Apr 01 14:59:27 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Brighter Than Sunshine" with Spotify URI "spotify:track:3W6UA36h0zahjxU709wL
Apr 01 14:59:27 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Brighter Than Sunshine" loaded
Apr 01 15:03:29 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Waves" with Spotify URI "spotify:track:5TBEr7fXO6cjnOHG3RQENk"
Apr 01 15:03:30 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Waves" loaded
Apr 01 15:06:43 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "No Matter - Acoustic" with Spotify URI "spotify:track:14OWlpPcJxsBvSGI4W65Hl
Apr 01 15:06:43 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "No Matter - Acoustic" loaded
Apr 01 15:09:37 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "13 Beaches" with Spotify URI "spotify:track:4mq14Qa6OehdiyZFtHcdCH"
Apr 01 15:09:37 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "13 Beaches" loaded
Apr 01 15:14:32 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Chandelier - Piano Version" with Spotify URI "spotify:track:1F42Ox5sB2wHdy3a
Apr 01 15:14:33 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Chandelier - Piano Version" loaded
Apr 01 15:18:33 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Cringe - Stripped" with Spotify URI "spotify:track:6TpowNTagUJ7f8ctFFCVN8"
Apr 01 15:18:33 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Cringe - Stripped" loaded
Apr 01 15:22:12 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Quiet - Stripped" with Spotify URI "spotify:track:60oCAd3gei66GObniGX4wV"
Apr 01 15:22:12 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Quiet - Stripped" loaded
Apr 01 15:25:40 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Over And Over Again" with Spotify URI "spotify:track:1X6kxrjWVWiKMqulM8XZpj"
Apr 01 15:25:41 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Over And Over Again" loaded
Apr 01 15:29:48 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Say Something" with Spotify URI "spotify:track:78TKtlSLWK8pZAKKW3MyQL"
Apr 01 15:29:48 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Say Something" loaded
Apr 01 15:33:38 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "When I Was Your Man" with Spotify URI "spotify:track:0nJW01T7XtvILxQgC5J7Wh"
Apr 01 15:33:38 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "When I Was Your Man" loaded
Apr 01 15:37:11 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Somewhere Only We Know" with Spotify URI "spotify:track:3DDGhkxq3FeUorZppSge
Apr 01 15:37:11 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Somewhere Only We Know" loaded
Apr 01 15:40:39 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Woman Go Wild" with Spotify URI "spotify:track:020YsiW7gnBiqTAmEg7eTc"
Apr 01 15:40:40 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Woman Go Wild" loaded
Apr 01 15:44:38 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Don't Kill My Vibe - Acoustic" with Spotify URI "spotify:track:48pYiPPXFoC8l
Apr 01 15:44:39 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Don't Kill My Vibe - Acoustic" loaded
Apr 01 15:47:45 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "What a Good Woman Does" with Spotify URI "spotify:track:1NnYLKwyk4PjliVayy4O
Apr 01 15:47:45 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "What a Good Woman Does" loaded
Apr 01 15:51:12 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "I Will Be Found (Lost At Sea)" with Spotify URI "spotify:track:05Ez6KwjICksc
Apr 01 15:51:12 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "I Will Be Found (Lost At Sea)" loaded
Apr 01 15:55:13 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Stay With Me" with Spotify URI "spotify:track:5Db9VIdDsN5yu3Eu7CT0i4"
Apr 01 15:55:13 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Stay With Me" loaded
Apr 01 15:58:06 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "All of Me" with Spotify URI "spotify:track:3U4isOIWM3VvDubwSI3y7a"
Apr 01 15:58:06 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "All of Me" loaded
Apr 01 16:02:35 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Great American Novel" with Spotify URI "spotify:track:6pdOd8gMlo8WcDQYSwXCDe
Apr 01 16:02:35 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Great American Novel" loaded
Apr 01 16:06:31 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Breathe (2 AM)" with Spotify URI "spotify:track:5auMzVHFr5Zfw6IbKarZ56"
Apr 01 16:06:31 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Breathe (2 AM)" loaded
Apr 01 16:11:11 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Shelter" with Spotify URI "spotify:track:1sLxooNd8EKRLDs0YiwbZF"
Apr 01 16:11:11 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Shelter" loaded
Apr 01 16:15:41 MediaCenter librespot[435]: INFO:librespot_playback::player: Loading track "Blackout" with Spotify URI "spotify:track:0bqQuzIX7tpY4IBllPHDqF"
Apr 01 16:15:42 MediaCenter librespot[435]: INFO:librespot_playback::player: Track "Blackout" loaded

**Comment by dthisner** [comment]
I have the same issue

**Comment by dtcooper** [comment]
Might you try the most recent version?

**Comment by agneevX** [comment]
Same issue here

```log
Aug 08 00:40:45 pi4 librespot[911]: [2020-08-07T19:10:45Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
```

**Comment by greyivy** [comment]
Same issue.

**Comment by JasonLG1979** [comment]
This is clearly and upstream issue. I would update to the latest version of Raspotify and if the issue persists file a bug report upstream with librespot.
