### ISSUE TITLE
Raspotify Slow Song

### ISSUE THREAD

**Issue by kolone13** [dtcooper/raspotify#194]
Hey,  i use osmc and installed Raspotify. It worked but the musicsound is slower and deeper.  It's like when i play the song in half speed.  How can i fix this?

**Comment by jeremymatthewwerner** [comment]
I'm having the same problem.
On stretch.

**Comment by jeremymatthewwerner** [comment]
I found a fix that worked for me here: https://askubuntu.com/a/1051160

Copy-and-pasting it here:

---
Press Ctrl+Alt+T to go to a terminal and use your favourite editor to edit the file

nano /etc/pulse/default.pa
then find a line containing:

load-module module-udev-detect
modify this to become:

load-module module-udev-detect tsched=0
save and exit and you're all set!
---

**Comment by kolone13** [comment]
Thank you very much!I tried it on stretch and it also worked for me. On osmc i didn't  had the problem after i enabled the airplay. So it was not nescessary to install raspotify
