### ISSUE TITLE
Update connection issue.

### ISSUE THREAD

**Issue by zivdarko** [dtcooper/raspotify#195]
Hey, firstly awesome thing you have built and thank you a lot.
Unfortunatelly can't connect since spotify got updated (version 8.4.98.892). Tried reinstalling, playing around with etc/default/raspotify but can't get it to connect. Am a beginner, so would appreciate some support

Thanks

**Comment by edegraaff** [comment]
I have updated my pi and it worked perfect at this moment. What i have observed the raspotify is sometimes not visible as play to availible device, but then from my telephone it is visible and works ok.
