### ISSUE TITLE
Invisible after using with another account

### ISSUE THREAD

**Issue by fankijo** [dtcooper/raspotify#203]
Hi, so just to clear things up, this peace of software is awesome!

So the raspotify device can be discovered on any Device in my LAN, just like it should. If Account 1 plays Music, it disappears. Still fine. But if Account 1 disconnects from the raspotify by switching the playback device back to smartphone or what else, the raspotify keeps beeing visible only to devices logged in to account 1. Devices with other accounts cant see the raspotify, until the serice is beeing restarted.

**Comment by spocon** [comment]
This is a good question for the actual programmers : https://github.com/librespot-org/librespot
