### ISSUE TITLE
Detect if music is playing

### ISSUE THREAD

**Issue by fankijo** [dtcooper/raspotify#204]
Hi,

I was wondering if there was any chance for other scripts running on the pi to detect wether Music is beeing played or not. My goal is to run a command as soon as msic is beeing played and run another command as soon as I disconnect my spotify off the raspotify.

**Comment by olafWal** [comment]
Add "--onevent /path/to/your/script" to librespot options

e.g.:
---------------8<----------------------
#! /bin/bash

logger $PLAYER_EVENT
logger $TRACK_ID
-------------->8----------------------------

$PLAYER_EVENT can be start|change|stop

**Comment by 20100times** [comment]
Hi

First thanks for your job, this tool is nice.
Like @fankijo I was wondering if I can run a python script (to turn on my hifi system) as soon as I start playing music on my raspberry pi.
@olafWal seems to have an idea about it but I can't figure his answer out.

Any help is welcome. Thank you for that.

**Comment by 20100times** [comment]
Hi @fankijo !

Did you manage to run a script when the music is played ?
Thanks
