### ISSUE TITLE
username

### ISSUE THREAD

**Issue by D3laz** [dtcooper/raspotify#234]
Sorry to ask but i cant find the right answer. 
I would like to know if its the e-mail or username or the username in spotify's account (like this 6vnmkn6r8i2ulo4wpy3bmgvhm). 
Do we have to uncomment line or not?
Thanks a lot

**Comment by jimjimjimjimjimjim** [comment]
Username it is. Uncomment line.

**Comment by vguttmann** [comment]
@D3laz Can confirm that. You could close this issue if that resolved your question.
