### ISSUE TITLE
switch to librespot-java

### ISSUE THREAD

**Issue by designandcopy** [dtcooper/raspotify#238]
switching to [librespot-java](https://github.com/librespot-org/librespot-java) might eliminate some reliability issues & give us a more fully-featured client

**Comment by spocon** [comment]
Please check out SpoCon :  https://spocon.github.io/spocon/

**Comment by spocon** [comment]
FYI : 

There is a new project with a Spotify GUI introduced in a new project called https://github.com/spocon/lovspotify  

For this i merged spocon and librespot-view and removed the project

I keep keep the spocon project alive but it doesn't include neither a GUI nor a REST-API
