### ISSUE TITLE
Like or Dislike unavailable when connecting to Raspotify Connect

### ISSUE THREAD

**Issue by Kia0ra** [dtcooper/raspotify#24]
The Like or Dislike commands disappear from the player as soon as the Raspotify Connect device is chosen to play audio. Instead the Random / Repeat commands appear.
Maybe this is a Librespot issue, I don't know

**Comment by nyxjemk** [comment]
I discovered the same, I find the buttons very useful for customising playlists.
Really would appreciate a solution for this!
