### ISSUE TITLE
how to upgrade raspotify and dependencies (like Librespot)

### ISSUE THREAD

**Issue by W-M-B** [dtcooper/raspotify#241]
Hi,
I experience issues, that my raspotify gets a timeout with Spotify regularly.
Therefore I want to upgrade raspotify including all dependant packages to the recent version before digging deeper.
But I cannot find a guide how to upgrade raspotify without breaking or overwriting the existeing configfile etc.
Any suggestion?
Regards, Wolfram

**Comment by spocon** [comment]
SpoCon 

https://spocon.github.io/spocon/

**Comment by vguttmann** [comment]
I would suggest making a copy of the config file before upgrading, as this should be a one-time action, and not something you'll do on a regular basis.
