### ISSUE TITLE
Raspotify overrides explicit content setting

### ISSUE THREAD

**Issue by JimVincent** [dtcooper/raspotify#242]
Hi

I am having an issue where I have my Spotify account set to NOT allow explicit content. However, when I connect to the Raspotify it allows explicit content to be played.

Is there any way I can set this setting  via the librespot config?

Thanks in advance and awesome project - I use it to control music at an ice-rink

Cheers,
Jim

**Comment by stephenglobal** [comment]
I've got the same issue. Have to glance at my playlists and set a reminder to skip songs after x amount of minutes. Hope they provide a fix for this.
