### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by null-von-sushi** [dtcooper/raspotify#243]
I am getting an error on install.

```
dpkg: error processing archive raspotify-latest.deb (--install):
 package architecture (armhf) does not match system (arm64)
Errors were encountered while processing:
 raspotify-latest.deb
```

This is on a raspberry Pi 4 Model B (iirc) running Ubuntu 19.10

**Comment by spocon** [comment]
Try SpoCon , it's build for armhf and arm64 

https://spocon.github.io/spocon/

**Comment by null-von-sushi** [comment]
> Try SpoCon , it's build for armhf and arm64
> 
> https://spocon.github.io/spocon/

Well it's been forever, and Ubuntu is a piece of shit, but I tried SpoCon on Raspbian and it works great so far. Thanks!
