### ISSUE TITLE
Raspotify is not visible.

### ISSUE THREAD

**Issue by TheDablet** [dtcooper/raspotify#245]
Hello!
I installed raspotify on Debian. After installation i tried to connect from Android app, but i can't see my device. Anyone knows solution?

**Comment by spocon** [comment]
are you in the same wlan as your raspotify ?

**Comment by spocon** [comment]
if it doesn't work you could also try librespot-java , i wrote a wrapper . It works with all debian based OS systems. 

https://github.com/spocon/spocon

**Comment by TheDablet** [comment]
A moment ago, I solved this problem. I just reinstalled Raspotify. Thank for reply.
