### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by FernonE** [dtcooper/raspotify#246]
I have a clean install of NOOB raspberry pi 3B+ and spotify sees the raspberry connect system but there is no sound. I've tested some normal audio which works fine and the raspberry does produce sound. I've no clue where to start debugging this. 

P.s. I've tried to look through the other issues. But haven't found a solution.

**Comment by spocon** [comment]
i have the same setup and use librespot-java. I wrote a installer for this : 

installation instruction is basically the same as with 

https://github.com/spocon/spocon

I didn't have to change anything and my spotify client connected and played my song right away without any changes.

**Comment by FernonE** [comment]
I've replaced my OS with debian lite and this for some reason directly solved my problem. I still have no clue why it didn't work in the first place though...
