### ISSUE TITLE
Possible to disable volume normalization?

### ISSUE THREAD

**Issue by markwheeler** [dtcooper/raspotify#248]
In `raspotify` config it states that _"By default, the volume normalization is enabled"_ and there is a flag for enabling it with custom options. But I see no flag for disabling it in the raspotify or librespot docs. Is this possible?

**Comment by thomasjonas** [comment]
I think you'll need to add `VOLUME_ARGS` in `/etc/default/raspotify` I think the default options for that argument are `VOLUME_ARGS="--enable-volume-normalisation --linear-volume --initial-volume=100"`, so you could just omit `--enable-volume-normalisation`
