### ISSUE TITLE
Last.fm Scrobbling

### ISSUE THREAD

**Issue by joeinnes** [dtcooper/raspotify#25]
Last.fm scrobbling is not available in Raspotify

**Comment by BonarBeavis** [comment]
This could help: [Scrobbler for Spotify Connect : lastfm](https://www.reddit.com/r/lastfm/comments/66psku/scrobbler_for_spotify_connect/)

**Comment by notABluesSinger** [comment]
See my comment on #69. This may be a non-issue now 🤞

**Comment by BonaBeavis** [comment]
Tested, It is.
