### ISSUE TITLE
Start Raspotify without sudo rights

### ISSUE THREAD

**Issue by map555** [dtcooper/raspotify#251]
Hi!
I tested raspotify some months ago and it just works fine.
Now, I'm trying to use raspotify into a university project but the problem is that raspotify needs the super user rights. Is there a way to run it without sudo?

Note: Sorry if my english is bad. It's not my first language.

**Comment by spocon** [comment]
Hej map,

[SpoCon](https://github.com/spocon/spocon) is a wrapper for librespot-java 's library by Gianluca Altomani. Spocon is similar to Raspotify but with two major 

- it has librespot-java in the background 
- it includes a REST-API where you can get pictures, text , song title  of the current song aso. [here is the link](https://github.com/librespot-org/librespot-java/tree/dev/api)

**Comment by spocon** [comment]
ah forgot the best reason... it doesn't need root access to start the application ;-)
