### ISSUE TITLE
Can't play this right now

### ISSUE THREAD

**Issue by frode** [dtcooper/raspotify#253]
Running the latest version of raspotify on a RPi3.
Yesterday it was working, today its not working anymore.

Getting this message:

"Can't play this right now" and when i mouse hover the message it says "Spotify is not active on this device"

![Screenshot 2020-03-11 at 13 30 00](https://user-images.githubusercontent.com/102189/76417111-8bd10200-639c-11ea-8efe-781cf953d266.png)

Have tried to check for updates on raspbian and rebooting does not help..

**Comment by koglevee** [comment]
Experiencing 'similar' problems.  Worked the morning of 3/12.  Ceased before ~12:pm EDT.  Fed by Win10.  Broke on-the-fly after a long and illustrious career, so...  anyone @Spotify have some insight before I start tearing things apart??

**Comment by dheckl** [comment]
I have the same issue and tested it with librespot standalone, but here is also the error. Are there any changes at Spotify which brakes librespot?

**Comment by frode** [comment]
I have not been using raspotify for months now and I wont be able to participate in any future testing

**Comment by fphammerle** [comment]
https://community.volumio.org/t/solved-spotify-connect-cant-play-this-right-now/6663/2 reports:
> Today, my devices show up in the devices list as “Can’t play this right now”. [...]
> For some reason, Spotify Connect does not work when playing podcasts! When switching to an actual song, the devices were available again!

I was able to select the librespot device after switching from a podcast to songs

**Comment by glensc** [comment]
duplicate: https://github.com/dtcooper/raspotify/issues/385

**Comment by rogerjbos** [comment]
Same experience here.  Anyone figure out why playing songs works fine but playing podcasts doesn't work?  Not critical, but it would be nice to listen to podcasts as well.

**Comment by JasonLG1979** [comment]
> Same experience here. Anyone figure out why playing songs works fine but playing podcasts doesn't work? Not critical, but it would be nice to listen to podcasts as well.

It's an upstream bug. It will likely get fixed when `librespot` finishes reverse engineering the latest Spotify playback API and starts supporting other formats besides just vorbis streams. It's not a Raspotify bug. Raspotify is just a packaged build of `librespot`. Please don't necro-bump closed issues with me too's.
