### ISSUE TITLE
Connection status

### ISSUE THREAD

**Issue by MarkusK1** [dtcooper/raspotify#255]
Raspotify is working excellent on my raspberry. 
Is it possible to read/find out the connection status? Because I want to turn on my amplifier automatically, if a cellphone is connected to raspotify.

**Comment by trizin** [comment]
You can use spotipy to check if your spotify streaming on a device 
[Docs here](https://spotipy.readthedocs.io/en/2.9.0/?highlight=devices#spotipy.client.Spotify.devices)

**Comment by g-philipp** [comment]
i want to do the same thing with the auto turn on amp
