### ISSUE TITLE
raspotify doesn't support architecture 'arm64'

### ISSUE THREAD

**Issue by JonathanGirardeau** [dtcooper/raspotify#263]
I've installed Ubuntu 64 bits 18.04.4 LTS on my raspberry pi and I faced some issues to install raspotify on it:
`> curl -sL https://dtcooper.github.io/raspotify/install.sh | sh`
`Raspotify installer only runs on a Raspberry Pi`
`> sudo apt-get update`
`...`
`N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://dtcooper.github.io/raspotify raspotify InRelease' doesn't support architecture 'arm64'`

I found this article on the net but it seems a bit dirty:
https://thewayeye.net/posts/installing-raspotify-arm64/

Do you plan to make raspotify compatible with Ubuntu 64 bits ? 
Or do you have tips to make it run ?

**Comment by spocon** [comment]
lovspotify does support arm64 

https://github.com/spocon/lovspotify

**Comment by tswindell** [comment]
Just run the below before installation:
`dpkg --add-architecture armhf`

**Comment by jodo234** [comment]
I successfully installed raspotify on my new RPi4 and I receive the same error/warning during apt-get update. Does this mean, I wont receive any updates unless I issued that command tswindell posted? Or will there be a arm64 release?

**Comment by JasonLG1979** [comment]
I would love to see native arm64 builds. PR's welcome!!!

**Comment by timfi-amsterdam** [comment]
Is anyone working on this? I'm not familiar with deb repos but after looking around a little bit I think it's not that hard.

**Comment by JasonLG1979** [comment]
> Is anyone working on this? I'm not familiar with deb repos but after looking around a little bit I think it's not that hard.

Then get if a shot. Like I said PR's welcome.

**Comment by timfi-amsterdam** [comment]
Great, I'm giving it a try

**Comment by JasonLG1979** [comment]
> Great, I'm giving it a try

In some distant future when Pi Zero V2's aren't unobtainium we will be able to drop support for Pi 1's and Pi Zero V1.x's and we'll be able to build 32 bit (ARMv7) and 64 bit ARM packages with just vanilla Debian and not have to pull in the ARMv6 toolchain.

**Comment by timfi-amsterdam** [comment]
@JasonLG1979 i've created a pull request. I was not sure how to test the actual repository though. Is there some documentation on this?

**Comment by JasonLG1979** [comment]
> I was not sure how to test the actual repository though. Is there some documentation on this?

No, not really I'm not really sure myself? I'd also like an x86_64 package while you're at it if you could so that we only need to bug @dtcooper once to do the repo set up. I think that if we have armhf, arm64, and amd64 that should cover just about everyone.

**Comment by JasonLG1979** [comment]
Well as far as I can tell everything went off without a hitch. amd64 would be nice but it's not a must.

**Comment by timfi-amsterdam** [comment]
Great! I'll have a look at amd64 when I find the time.

**Comment by JasonLG1979** [comment]
> Great! I'll have a look at amd64 when I find the time.

Sounds good, no rush. Another more pressing concern is that the soon-ish to be merged `new-api` `libresopt` branch does not compile (for ARMv6 anyway) with our current toolchain. I have not tried since your commit so I'm not sure if it works for arm64 either? My hope is that it's just a matter of tweaking something small for it to work for ARMv6 otherwise we would have to drop ARMv6 support which would be a bummer for Pi Zero users but would simplify our build process since everything could come directly from Debian as it does with the arm64 build.

**Comment by JasonLG1979** [comment]
@timfi-amsterdam never mind I copypasta'd your PR and hacked in x86_64 support.

**Comment by timfi-amsterdam** [comment]
> > Great! I'll have a look at amd64 when I find the time.
> 
> Sounds good, no rush. Another more pressing concern is that the soon-ish to be merged `new-api` `libresopt` branch does not compile (for ARMv6 anyway) with our current toolchain. I have not tried since your commit so I'm not sure if it works for arm64 either? My hope is that it's just a matter of tweaking something small for it to work for ARMv6 otherwise we would have to drop ARMv6 support which would be a bummer for Pi Zero users but would simplify our build process since everything could come directly from Debian as it does with the arm64 build.

I looked at the librespot examples and I think that as long as they support armv6 it won't be hard to port that. If they decide to drop support, it might be time to also just go that route?

**Comment by JasonLG1979** [comment]
> I looked at the librespot examples and I think that as long as they support armv6 it won't be hard to port that. If they decide to drop support, it might be time to also just go that route?

The build scripts in the contrib folder aren't well maintained. Being in contrib they're not really used regularly during development and are not tested when changes are made like the core code base. I personally basically ignore everything in the contrib folder. I would not count on them actually working all of the time.

**Comment by JasonLG1979** [comment]
In my mind we are basically the example of how to build `librespot` in the wild.
