### ISSUE TITLE
change default volume

### ISSUE THREAD

**Issue by g-philipp** [dtcooper/raspotify#265]
Is it possible, to cange the default volume? When I connect, the volume is always 100%, can I somehow change it?

**Comment by g-philipp** [comment]
Found it out myself, so you have to stop the service with `systemctl stop raspotify.service
` edit this file: `/lib/systemd/system/raspotify.service` with nano or something else (with root) and then change the `--initial-volume=20"` to 20 or something else. Then you have to reload the deamon with `systemctl daemon-reload` and then start the raspotify service with `systemctl start raspotify.service`

**Comment by Intruder66** [comment]
Please close this issue then.
