### ISSUE TITLE
librespot's pleitar has quit, maybe change fork?

### ISSUE THREAD

**Issue by markheloking** [dtcooper/raspotify#27]
The original dev of pleitar has announced that due to personal circumstances (a new job or something) he's no longer able to work on librespot, and he actively stops maintaining it (including handling issues and reviewing pull requests).
Maybe we should start considering taking librespot from an alternative active fork? Looking at the network graph then [michaelherger's](https://github.com/michaelherger/librespot) fork seemed pretty active up until a month ago.

**Comment by dtcooper** [comment]
Thanks for the heads up. When a clear authoritative fork arrises, I'll switch over.

**Comment by dtcooper** [comment]
@markheloking Will keep an eye on it, thank you
