### ISSUE TITLE
Not Playing Local Files

### ISSUE THREAD

**Issue by AfroPsycho** [dtcooper/raspotify#272]
Hi 
I am using raspotify on a raspberry pi zero W with no issues 
but today i added few local songs to the spotify I can play them on my pc I can play them on my phone but when I connect to the raspotify there is no sound
it can play other song without any problem but only local songs
I have a guess for playing local files on your phone you should add songs from pc than create a playlist after that you should download that playlist in your phonw while youre connected the same network as your pc
So I think because of I didnt download the playlist on the raspberry it cannot play
is there a way to download the playlist to the raspotify?
or is it another issue I cant see 
At the end raspotify cant play local files if it is not an issue it can be a feature request

**Comment by Yusaki-Akito** [comment]
I have same issues but on raspberry pi 4 Debien Lasted version was update on 5 days ago 

On sound test raspberry pi can play some sound test and on browser is working fine I think it cus raspotify that has no sound I have already config on the config file add --driver something like that but still not work
