### ISSUE TITLE
No sound | Just streamming without sound

### ISSUE THREAD

**Issue by Yusaki-Akito** [dtcooper/raspotify#273]
Issues on raspberry pi 4 Debien Lasted version was update on 5 days ago

On sound test raspberry pi can play some sound test and on browser is working fine I think it cus raspotify that has no sound I have already config on the config file add --driver something like that but still not work

**Comment by saptarshimanna** [comment]
Same problem happened to me. I did two things.
1. Type alsamixer on terminal select sound card as the desired one. Note down the serial number.
2. In raspotify config file type OPTIONS="--device hw:<serial number you noted>", save and restart

**Comment by Yusaki-Akito** [comment]
I don't know why sometime work sometime not
