### ISSUE TITLE
Running raspotify on a server

### ISSUE THREAD

**Issue by saptarshimanna** [dtcooper/raspotify#274]
Pi is a very capable device, we all agree to that. So instead of handling one task, I wanted to make it handle multiple tasks. I use pi as a wireless access point in my home. It runs DHCP and DNS server using dnsmasq. As the pi remains always on, I wanted to run raspotify on this device, so that I could get music anytime I want. And I do not have to shell out another pi for this. But it seems raspotify works only on the client devices, devices that are connected to a router, not on a router itself. This could be a problem worth solving for. Anybody has any idea on hoe to fix this. pi's wlan interface has a static ip.

**Comment by T0BiD** [comment]
How do you come to the conclusion, that this doesn't work, because it works perfectly fine for me.
