### ISSUE TITLE
Raspotify not picked up by connect control for Alexa.

### ISSUE THREAD

**Issue by Jezza2** [dtcooper/raspotify#278]
I've got raspotify running on a Pi Zero W, but I can't control it with my echo dot because this skill: https://www.amazon.co.uk/Lawrence-Thorpe-Connect-Control-Spotify/dp/B074KFNWFD can't find it.  Obviously I'm not sure where the issue is; whether it's with raspotify, librespot, or with the skill itself.  I thought I'd start here to see if you can shed some light on where it might be.  Thanks!

**Comment by AngeloAvv** [comment]
Hi @Jezza2 , have you figured out how to control raspotify over the Alexa's skill you have linked here? I have the same problem

**Comment by drkostas** [comment]
I am also interested in knowing the solution to this
