### ISSUE TITLE
Gapless playback support

### ISSUE THREAD

**Issue by francisywk** [dtcooper/raspotify#283]
Currently there is a gap in between songs. Librespot has added support for it. Can this be supported as well on raspotify? librespot-org/librespot#430

**Comment by andrewboie** [comment]
Immediately noticed this as well. Is it just a matter of pulling up to a new version of librespot? What I have from the PPA is `raspotify/unknown,now 0.14.0~librespot.20200130T014147Z.3672214`, the librespot change went in February, so it seems the librespot is just a touch out of date. I'm going to see if I can compile everything from source.

**Comment by dtcooper** [comment]
Supported now!
