### ISSUE TITLE
Enabling compatibility of Spotify Connect with free accounts

### ISSUE THREAD

**Issue by ahnafa** [dtcooper/raspotify#284]
Since Spotify Connect is a feature available in non-Premium accounts as well, would it be possible to update the software to ensure compatibility with free user accounts?

**Comment by dtcooper** [comment]
This feature is not available in the underlying library, [librespot](https://github.com/librespot-org/librespot), so closing. You could elect to file a ticket on that project.

**Comment by ahnafa** [comment]
Gotcha, cheers!
