### ISSUE TITLE
New upstream release July 2020

### ISSUE THREAD

**Issue by artmg** [dtcooper/raspotify#286]
Hi @dtcooper  many thanks for packaging librespot in such an easily usable way. I just wanted you to know that ls.org have just released a new version https://github.com/librespot-org/librespot/releases/tag/v0.1.2 so when you next get the opportunity to cut a new release yourself, that would be much appreciated.

**Comment by dtcooper** [comment]
Thanks for flagging this. On it now!

**Comment by dtcooper** [comment]
Done!
