### ISSUE TITLE
libmdns error sending packet

### ISSUE THREAD

**Issue by ewouddeenik** [dtcooper/raspotify#288]
After installing Pi-hole on my RPI4 raspotify suddenly does not work anymore.
When asking for the status, this is the reply.
`pi@Gaia:~ $ sudo service raspotify status
● raspotify.service - Raspotify
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-08-04 21:13:06 BST; 9s ago
  Process: 15977 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCE
  Process: 15978 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, statu
 Main PID: 15979 (librespot)
    Tasks: 6 (limit: 4035)
   Memory: 1.3M
   CGroup: /system.slice/raspotify.service
           └─15979 /usr/bin/librespot --name Soundscape system --backend alsa --bitrate 320 --cache /

Aug 04 21:13:06 Gaia systemd[1]: Starting Raspotify...
Aug 04 21:13:06 Gaia systemd[1]: Started Raspotify.
Aug 04 21:13:06 Gaia librespot[15979]: [2020-08-04T20:13:06Z INFO  librespot] librespot (raspotify v0
Aug 04 21:13:06 Gaia librespot[15979]: [2020-08-04T20:13:06Z WARN  libmdns::fsm] error sending packet`

I noticed the last line and think this has something to do with the installment of pihole.  but I do not know where to start to fix it.
Does anybody have some tips or tricks to fix this issue?

**Comment by JasonLG1979** [comment]
This would be something to ask the PiHole folks.
