### ISSUE TITLE
Track information on an LCD display

### ISSUE THREAD

**Issue by Gadgetoid** [dtcooper/raspotify#294]
Ahoy!

A few of our Pirate Audio customers have expressed a keen interest in better Raspotify support for our Raspberry Pi add-on boards. That means displaying album art and track information on the LCD display.

To that end I have started work on the PiDi Spotify project- a client/server Python program that interprets the `--onevent` hook environment variables that Raspotify (librespot?) uses, fetches data from Spotify's API and displays it on our 240x240 colour LCD.

I appreciate this isn't an *issue* per se, but I would like to bring this to the attention of Raspotify users because:

1. I think they'll find it interesting
2. Potentially it could be integrated into Raspotify when it's mature and stable enough
3. I'm keen to know if there are any other LCD display products in common use that might be worth supporting
4. Bouncing a dozen people off this will keep me motivated to clean it up and finish it, and help bash off the rough edges

If this sounds interesting, you can find the beta here - https://github.com/pimoroni/pidi-spotify

Thank you!

**Comment by dtcooper** [comment]
If you'd like to submit a PR editing the Readme with a link/description in a newly created FAQ sections, I'll link out to your project!
