### ISSUE TITLE
Still visible in other networks after disconnecting.

### ISSUE THREAD

**Issue by Marthaarman** [dtcooper/raspotify#313]
In contrast to devices such as a Chromecast, the raspotify cast option stays visible within spotify when i move tho a whole new location / network. This is only ofcourse when i have connected to the raspotify once but should not be there any longer such that i cannot play music on a location i'm not present in. 

What is the solution to this, is this a bug or a setting i missed?

**Comment by JasonLG1979** [comment]
raspotify is just a thin wrapper around [librespot](https://github.com/librespot-org/librespot). You should file a bug report with them about this.
