### ISSUE TITLE
hashtag in username doesn't seem to work

### ISSUE THREAD

**Issue by xavuk** [dtcooper/raspotify#317]
Hello,

I have a # in my username and the following happen :
WARN  librespot_core::mercury] error 404 for uri hm://remote/user/#...

Device is visible but stop at "connecting".

**Comment by JasonLG1979** [comment]
Currently you can't use a username or password with special characters in raspotify. I would consider it a bug myself but I haven't really looked into it much because it doesn't affect me. PR's are welcome I'm sure.
