### ISSUE TITLE
Attempt to see if raspotify is streaming

### ISSUE THREAD

**Issue by hidenbiden22** [dtcooper/raspotify#327]
Hello,
I can't seem to find a way to tell if raspotify is streaming, and what song is playing. Is there some way to do that? Thanks!

**Comment by JasonLG1979** [comment]
Your ears?

**Comment by JasonLG1979** [comment]
In all seriousness you can use an "onevent" script:
https://github.com/librespot-org/librespot/issues/185

**Comment by hidenbiden22** [comment]
That sounds great! Thanks for your help. I got it up and running.

**Comment by controlcde** [comment]
@hidenbiden22 I'm looking for something similar: Would you please share your onevent script?
