### ISSUE TITLE
Home Assistant lovelace media player control - Raspotify

### ISSUE THREAD

**Issue by Nird91** [dtcooper/raspotify#328]
Hi, thanks for this project,
it would be interesting to integrate the music controls on home assistant interface (lovelace), as happens for example between a chromecast/nest audio and home assistant. I don't know if this can be very difficult. :)
(I'm sorry for my english)

![image](https://user-images.githubusercontent.com/61241436/100596804-dd3f6980-32fc-11eb-9c8c-caadd51fdbc5.png)

or

![image](https://user-images.githubusercontent.com/61241436/100596836-e9c3c200-32fc-11eb-8cde-aa89bb59320f.png)

**Comment by JasonLG1979** [comment]
Raspotify is a thin wrapper around librespot. Librespot is purposely minimal. It provides no method to control Spotify and very, very  little metadata information. What you're looking for is [Spotifyd](https://github.com/Spotifyd/spotifyd) it uses MPRIS and I believe maybe even has a websocket API(?).
