### ISSUE TITLE
Raspotify not visible

### ISSUE THREAD

**Issue by Finnitio** [dtcooper/raspotify#329]
Raspotify disappeared from all my devices, without any cromprehensible reason. I removed it completely and reinstalled it which fixed the problem for a short while. Now I can't see it anymore. All other devices are visible.

**Comment by Tiemon-hoi** [comment]
i have the same problem. just since 2 days. i cant find a solution either

**Comment by febs** [comment]
This actually happened to me as well exactly two days ago. I wonder if Spotify changed anything of its APIs during that time.

**Comment by Finnitio** [comment]
I did a clean new install of buster and now it works again.
