### ISSUE TITLE
Cannot play through headphone jack

### ISSUE THREAD

**Issue by tomdlmurphy** [dtcooper/raspotify#337]
Hi!

I'm not able to force the sound to come out of the headphone jack; it just stays on the HDMI output. I've using `raspi-config` to set the sound to headphone jack. I've also tried using just the desktop sound icon. I know it's something wrong with raspotify because I can get sound through the headphone jack with other applications (youtube on chromium). I've taken advice from [this post](https://github.com/dtcooper/raspotify/issues/22), but when when I add

`OPTIONS="--onstart 'sudo amixer cset numid=3 1' --onstop 'sudo amixer cset numid=3 0'"`

to the conf file in /etc/default the service no longer works. Here is the output from sudo service raspotify status:

`● raspotify.service - Raspotify
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-12-20 09:28:05 EST; 8s ago
  Process: 5554 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 5555 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 5556 ExecStart=/usr/bin/librespot --name ${DEVICE_NAME} $BACKEND_ARGS --bitrate ${BITRATE} $CACHE_ARGS $VOLUME_ARGS $OPTIONS (code=exited, status=1
 Main PID: 5556 (code=exited, status=1/FAILURE)

Dec 20 09:28:05 raspberrypi librespot[5556]:                         Play all tracks at the same volume
Dec 20 09:28:05 raspberrypi librespot[5556]:         --normalisation-pregain PREGAIN
Dec 20 09:28:05 raspberrypi librespot[5556]:                         Pregain (dB) applied by volume normalisation
Dec 20 09:28:05 raspberrypi librespot[5556]:         --linear-volume
Dec 20 09:28:05 raspberrypi librespot[5556]:                         increase volume linear instead of logarithmic.
Dec 20 09:28:05 raspberrypi librespot[5556]:         --autoplay      autoplay similar songs when your music ends.
Dec 20 09:28:05 raspberrypi librespot[5556]:         --disable-gapless
Dec 20 09:28:05 raspberrypi librespot[5556]:                         disable gapless playback.
Dec 20 09:28:05 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
Dec 20 09:28:05 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
`

Here are the extra options I've added to my raspotify file in /etc/default

OPTIONS="--device hw:1,1"

OPTIONS="--username myuser --password mypass"

OPTIONS="--onstart 'sudo amixer cset numid=3 1' --onstop 'sudo amixer cset numid=3 0'"

Any help would be much appreciated! Super excited to use this! Thanks @dtcooper

**Comment by tomdlmurphy** [comment]
Just figure it out! I was redefining my options variable so it wasn't taking the device argument. Haha embarassing. For those not clear the line used to get audio from the headphone jack would be:

`OPTIONS="--username myuser --password mypass --device hw:1,0"`

The number after `hw` may vary. You need to run `aplay -l` in the terminal to see what number correspond to your headphone jack. The first number represents the card number, the second number represents the subdevice number.

**Comment by dtcooper** [comment]
Awesome! Closing, however please feel free to add the hot tip in the README or wiki. :)
