### ISSUE TITLE
How to restart raspotify automatically on connection error

### ISSUE THREAD

**Issue by faaafo** [dtcooper/raspotify#338]
Every fortnight or so I notice that raspotify is gone and check it with

`root@raspberrypi:~# systemctl status raspotify`

    ● raspotify.service - Raspotify
       Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
       Active: active (running) since Sun 2020-12-20 19:16:24 CET; 14h ago
      Process: 2854 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
      Process: 2855 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
     Main PID: 2856 (librespot)
        Tasks: 2 (limit: 1635)
       CGroup: /system.slice/raspotify.service
               └─2856 /usr/bin/librespot --name raspotify (raspberrypi) --backend alsa --bitrate 160 --disable-audio-cache --enable-volume-normalisation --linear-volume --initial-volume=100 --username foo --password bar
    
    Dec 20 19:16:24 raspberrypi systemd[1]: Starting Raspotify...
    Dec 20 19:16:24 raspberrypi systemd[1]: Started Raspotify.
    Dec 20 19:16:24 raspberrypi librespot[2856]: [2020-12-20T18:16:24Z INFO  librespot] librespot (raspotify v0.14.0) 6aac8a6 (2020-07-24). Built on 2020-07-26. Build ID: wPNyqn0m
    Dec 20 19:16:24 raspberrypi librespot[2856]: [2020-12-20T18:16:24Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }
    Dec 20 19:16:34 raspberrypi librespot[2856]: [2020-12-20T18:16:34Z WARN  librespot_core::apresolve] Failed to resolve Access Point: HTTP error
    Dec 20 19:16:34 raspberrypi librespot[2856]: [2020-12-20T18:16:34Z WARN  librespot_core::apresolve] Using fallback "ap.spotify.com:443"
    Dec 20 19:16:34 raspberrypi librespot[2856]: [2020-12-20T18:16:34Z INFO  librespot_core::session] Connecting to AP "ap.spotify.com:443"
    Dec 20 19:16:44 raspberrypi librespot[2856]: [2020-12-20T18:16:44Z ERROR librespot] Could not connect to server: failed to lookup address information: Temporary failure in name resolution

Now I restart `systemctl restart raspotify`and everything works again.

Has someone solved my steps above as script e.g. watchdog systemd?

**Comment by dtcooper** [comment]
Hopefully the newest tag, 0.16.0 fixes this. If it does not, please re-open.
