### ISSUE TITLE
ARM 64 support

### ISSUE THREAD

**Issue by dusatvoj** [dtcooper/raspotify#339]
Hi, there are a lot of ARM64 OSes for RPi. RaspberryPi OS will be 64bit in a while too.
Is there a possibility to build ARM64bit images? :thinking:
Thank you

**Comment by thorstenhaga-tradedoubler** [comment]
[Spocon](https://github.com/spocon/spocon) has arm64 already and others too

 spocon_1.5.2_amd64.deb (11.6 MiB)
spocon_1.5.2_arm64.deb (11.6 MiB)
spocon_1.5.2_armhf.deb (11.6 MiB)
spocon_1.5.2_i386.deb (11.6 MiB)
spocon_1.5.2_ppc64el.deb (11.6 MiB)
spocon_1.5.2_s390x.deb (11.6 MiB

**Comment by spocon** [comment]
https://github.com/spocon/spocon . Basically the same but more package support :

 spocon_1.5.2_amd64.deb (11.6 MiB)
spocon_1.5.2_arm64.deb (11.6 MiB)
spocon_1.5.2_armhf.deb (11.6 MiB)
spocon_1.5.2_i386.deb (11.6 MiB)
spocon_1.5.2_ppc64el.deb (11.6 MiB)
spocon_1.5.2_s390x.deb (11.6 MiB)

**Comment by dtcooper** [comment]
Not for this latest release, but yes. I'll put that on the roadmap. 🥇

**Comment by insign** [comment]
Just here to cry.

**Comment by pghpete** [comment]
It is a bit hackish, but this may be worth a try in the mean time... [](https://thewayeye.net/posts/installing-raspotify-arm64/)

**Comment by zhuykovkb** [comment]
> It is a bit hackish, but this may be worth a try in the mean time... https://thewayeye.net/posts/installing-raspotify-arm64/
> 
> I am running Ubuntu 20.10 for the raspberry pi which is also arm64.

awesome trick!

**Comment by JasonLG1979** [comment]
PR's welcome!!!

**Comment by JasonLG1979** [comment]
Duplicate of https://github.com/dtcooper/raspotify/issues/263
