### ISSUE TITLE
password crypto

### ISSUE THREAD

**Issue by Wqrld** [dtcooper/raspotify#34]
would it be possible to encrypt the spotify password so people shouldersurfing or people finding a way into your raspberry can't easily just see your password in plaintext?

low priority but useful

**Comment by dtcooper** [comment]
Kind of, sort of, not really. You can login in your browser at spotify.com,

Profile > Account > Set Device Password. Then you'll have a numeric username with a obfuscated, long, weird password.

Hope that helps!

**Comment by Wqrld** [comment]
i dont see a "device password" option anywhere

**Comment by dtcooper** [comment]
Hmmm, maybe it's only available to accts linked with Facebook. This would
be a librespot issue, IHMO

**Comment by Wqrld** [comment]
since librespot requires it as a command parameter(?) wouldnt it be possible to add a seperate field for a basic encrypted password that is decrypted my raspotify itself?
