### ISSUE TITLE
Click noise when skipping songs

### ISSUE THREAD

**Issue by febs** [dtcooper/raspotify#346]
I am experiencing the opposite issue as this: https://github.com/dtcooper/raspotify/issues/231

This is happening on a raspberry Pi zero with a DAC hat board.
raspotify version 0.16.0~librespot.v0.1.3-37-g0adb851 armhf

If I allow the music to flow from a tune to another everything works flawlessly. 
If I skip manually to another tune, then I hear a popping sound similar to a clipping one. 

The logs don't report anything problematic.

**Comment by jackobtone** [comment]
In my case, when I skip songs it sounds like spotify is replaying 1-2sec of last song.

**Comment by oskarnilsson** [comment]
I have the exact same issue. A loud crackling sound when skipping or changing song. Using a Pi Zero and playing through the USB which is plugged into my dac/amp.

**Comment by JasonLG1979** [comment]
The new release is live. Please update and see if that solves your issue.

**Comment by JasonLG1979** [comment]
This is an upstream issue. If after updating to the latest version of Raspotify the issue persists please file a bug with librespot.
