### ISSUE TITLE
Raspotify lirc IR control

### ISSUE THREAD

**Issue by jackobtone** [dtcooper/raspotify#348]
Hi! Is it or will it be possible (in near future) to control raspotify using lirc? Ex such functions as skipping tracks, start, play would be much appreciated!
Thanks :)

**Comment by jackobtone** [comment]
Isn`t there really any way to make it work together?

**Comment by neilbags** [comment]
I reckon you could do this using raspotify for playback and another tool to control it. I'm seeing spotify-cli, and spotipy as potential options. Might do a write-up if I make this work
