### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by juanca1944** [dtcooper/raspotify#36]
Hello!

I can see "raspotify (raspberry pi)" under "Devices Available" but doesn´t connect, using Android.

Thanks for your help

**Comment by mmarcm** [comment]
Is it only on Android? I had the same issue when I made a mistake in the OPTIONS line in `etc/default/raspotify` 
If you uncomment OPTIONS and don't delete / fill in username & pw then it has problems connecting (at least for me).

**Comment by juanca1944** [comment]
Thank you for your answer, I´ll follow your advice, and let  you know.

Regards

**Comment by cnmicha** [comment]
Where do I need to fill in the login data instead of putting them into the OPTIONS? Is there a workaround?
