### ISSUE TITLE
"Can't play this right now"

### ISSUE THREAD

**Issue by etannerm** [dtcooper/raspotify#361]
Hello,

I am having some difficulty with my config file. When I try to stream using my phone as a controller, I get the "Can't play this right now" message under a greyed-out raspotify option. My config file is attached.
[raspotify config etannerm.txt](https://github.com/dtcooper/raspotify/files/5912377/raspotify.config.etannerm.txt)

I think the problem is with the "--device" line, but I don't know what to change it to. I am using a HiFiBerry DAC2 HD, if that helps.

Please help!

**Comment by dtcooper** [comment]
You need to put this in an environment variable, not just in the middle of the text file, for example,

```
OPTIONS="--username <haha> --password <nottelling> --device snd_rpi_hifiberry_dacplushd"
```
