### ISSUE TITLE
Minor Issue. Changing the device name in settings doesn't change name on spotify app.

### ISSUE THREAD

**Issue by fffelan1** [dtcooper/raspotify#364]
Has anyone tried changing the name with success?

**Comment by Elalith** [comment]
Certainly! Where did you change your device name? You choose a name via raspi-config (which is used for showing a device name in your network and via the config file (which is used to define the name you see in Spotify).
`sudo nano /etc/default/raspotify`
Don't forget to remove the #-sign
`DEVICE_NAME="raspotify"`

If you've done that... It is possible that you only need to restart the raspotify service by using:
`sudo systemctl restart raspotify`
