### ISSUE TITLE
I just have a question: Does it use/need a GUI? Or can it run on a CLI setup?

### ISSUE THREAD

**Issue by Simao-Santos** [dtcooper/raspotify#365]

**Comment by Elalith** [comment]
It doesn't even have a GUI ;) I'm running Raspotify on my headless Raspberry Pi Zero W, which is connected to my 80's audioreceiver. I'm "casting" songs through the Spotify desktop app and the mobile app.

**Comment by Simao-Santos** [comment]
@Elalith are you using a hifiberry to connect to the 80s receiver?

**Comment by Elalith** [comment]
Nope, I'm using a [Pimoroni PHAT DAC](https://shop.pimoroni.com/products/phat-dac), but it should work with any DAC.

**Comment by Simao-Santos** [comment]
Nice I was looking for something like that!
Did you have to solder anything? Do you recommend it?

**Comment by Elalith** [comment]
I had to solder the female header on the DAC, but that's an easy thing to do.

**Comment by Simao-Santos** [comment]
The only problem is I don't have a solder 😓
Can you recommend a very simple cheap USB solder or something?
Thanks for the help eheh

**Comment by Elalith** [comment]
any cheap 12/25watt soldering iron will do ;) and it helps if you get tin with a flux core. Personally I use Griffon 99/1 (tin/copper).

But finding a HiFiBerry DAC+ Zero is propably easier ;) They have an presoldered header.

**Comment by Elalith** [comment]
If you lived anywhere near where I live, I would solder it for you ;)

**Comment by Elalith** [comment]
This is a very usefull tutorial: https://youtu.be/8Z-2wPWGnqE
