### ISSUE TITLE
Shuffle songs is out of sync with App sometimes

### ISSUE THREAD

**Issue by nkappler** [dtcooper/raspotify#367]
Sometimes, shuffle is turned of in the spotify app, but on the Pi the songs are shuffled nonetheless.

I haven't figured out yet how to reproduce this, or how to get it back in sync, but turning shuffling on and off and switching to next/previous songs seems to work sometimes.

**Comment by JasonLG1979** [comment]
Raspotify is just a packaged version of librespot this is an upstream issue.
