### ISSUE TITLE
Raspotify volume

### ISSUE THREAD

**Issue by wrskalle** [dtcooper/raspotify#37]
When i start a song in spotify app and choose my app to stream the song it always start at 100% volume.
Is there anyway to change this?
Mabey start att 10% volume.

Right now im sending the sound through hdmi to my reciever but will soon install a digiamp+.
Will this change anythin?
Best Regards
WRSKalle

**Comment by markheloking** [comment]
Duplicate of https://github.com/dtcooper/raspotify/issues/33.

**Comment by vguttmann** [comment]
If the issue is solved/covered somewhere else, you should close it @wrskalle
