### ISSUE TITLE
very low sound volume

### ISSUE THREAD

**Issue by MrLAtt** [dtcooper/raspotify#372]
I had raspotify setup on a Pi that had been working for around 6 months, however the SD card recently became corrupted, so I setup another one.

This time I've had a few problems though, I originally had issues with no sound, and [followed this ](https://github.com/dtcooper/raspotify/issues/31) to resolve it.

the sound now works, however it is very quiet.

The one thing I have noticed that is different from before is that the audio Icon in the top right of the display now shows full volume, whereas the old installation had what looked like a mute symbol, but when hovering over it it said something along the lines of ' this device has no audio control'

Does anyone know what my issue could be?

also, a less major problem, I can't seem to change what the Pi shows up as on spotify, despite changing the device name in the raspotify file, and many reboots/ dameon restarts.

Does anyone know what that could be?

**Comment by MrLAtt** [comment]
Just a note, yes, volume on spotify, the Pi in the Gui and on alsamixer are all at 100%

**Comment by jeremyehack** [comment]
Exact same issue here. I'm getting analog out audio but it's extremely low volume (like medium level with my speaker maxed.)

alsamixer has it at 100.
pavucontrol (pulse) cannot find any output devices

Just like you, when I right click the audio icon, it also cannot find any output devices. 

I'm on a pi 3b+

**Comment by zigutt** [comment]
@jeremyehack switch alsamixer soundcard (F6) to Headphones, helped me.

**Comment by alcalawil** [comment]
any news? same issue

**Comment by jeremyehack** [comment]
@alcalawil I did a clean install of Raspbian and it seemed to fix it.
