### ISSUE TITLE
Topping d10s and Bitrate 160 / 320

### ISSUE THREAD

**Issue by Zmperion** [dtcooper/raspotify#375]
Im using a topping d10s as a DAC between my Pi and amplifier. The D10s displays 48.0 when playing music in spotify, so apparently raspotify still outputs at the 160 Bitrate. 

Im new to using the Pi so maybe i'm doing something wrong. But i changed the Bitrate  (to 320) in the /lib/systemd/system/raspotify.service and in the /etc/default/raspotify

Did I do something wrong or am i missing something here? Tnx.

**Comment by fruitofgeorge** [comment]
I'm pretty sure the DAC is displaying the sample rate, not the bitrate.

**Comment by JasonLG1979** [comment]
@fruitofgeorge is correct. 48.0 is the sample rate as in 48khz.
