### ISSUE TITLE
problem: force to use USB audio card won't work.

### ISSUE THREAD

**Issue by nikogusm** [dtcooper/raspotify#379]
Hi. I have Raspberry Pi OS installed with a docker container containing Home Assistant.
The problem is that the home assistant container overwrites Raspotify audio output and I don't hear nothing when I connect my USB audio card.

Is there a way to disable docker audio and force original source audio output from Raspotify?

Thanks

**Comment by JasonLG1979** [comment]
You need to file an issue with Home Assistant or where ever you got the docker container from and ask them how to prevent it from breaking audio for Raspotify.
