### ISSUE TITLE
Unavailable to control / can't play this right now

### ISSUE THREAD

**Issue by SirCameron** [dtcooper/raspotify#385]
I'm having issues with the device being avaialable to connect to.
Changing the name or type of device and then restarting raspotify will update in Spotify on my computer and phone, but both remain greyed out with the above message.

Anyone else had this issue and know how to solve it?

Edit: I have a JustBoom DAC on pi, in case that helps.

**Comment by github42069420** [comment]
currently have this issue.

**Comment by KSuondProject** [comment]
Same here.
From fresh install no way to use raspotify. 
No error displayed on the systemctl status but when connected the track doesn't starts and after 2 secs spotify chose another device to stream.

**Comment by ConorShore** [comment]
I had this problem when the device you're trying to connect to doesn't exist. This happened for me when i unplugged the display from my Pi, moving my DAC from hw:3 to hw:2. Raspotify would appear, I'd try to play a song and it'd look like it was working for a few seconds then just disconnect.  Try following the instructions in my pull request, and let me know if it works, or you have any comments! (https://github.com/dtcooper/raspotify/pull/386). The instructions are in the config file

**Comment by dmtroyer** [comment]
I had this issue on multiple devices even after restarts. It came back after starting and stopping a couple of songs in Spotify.

**Comment by luthor112** [comment]
I have the same problem.

**Comment by luthor112** [comment]
I might have found the cause (in someone else's comment on another website): This only works for Spotify Premium users.
I bought Premium and now it works.

**Comment by iorippi** [comment]
@luthor112 I'm Premium account user so it can't be the reason.

**Comment by glensc** [comment]
It worked yesterday for me with same docker image, the only thing that may have changed meanwhile is that I played around with `amixer cset` settings.

I can hear sound fine when I play the sound in docker container with aplay, but starting the librespot ends up with new device appearing, but grayed out with status "Unable to control".

```
aplay -D hw:CARD=Headphones,DEV=0 /usr/share/sounds/alsa/Front_Center.wav
librespot --backend alsa --bitrate 320 --disable-audio-cache --enable-volume-normalisation --name hello6 --device hw:CARD=Headphones,DEV=0
```

**Comment by JasonLG1979** [comment]
> I can hear sound fine when I play the sound in docker container with aplay, but starting the librespot ends up with new device appearing, but grayed out with status "Unable to control".

@glensc That could be a few different things. Most of which have nothing to do with Raspotify/librespot.

The 1st and easiest possibility is that maybe you don't have a Spotify Premium account? A Spotify Premium account is required.

The 2nd is that it's a network configuration issue. Running Raspotify in a docker container is not really a supported use case, that is to say I will not offer help in regards to how to configure your docker container's network. Generally speaking I don't offer much networking help at all even on native Raspotify installs. This isn't a network help forum, sorry.

Raspotify is a packaged version of librespot. Aside from basic alsa configuration if it's not a packaging issue it's not a Raspotify problem.

I can't tell you what's going on though  in your case because you have not provided any logs so I can only guess at this time.

**Comment by glensc** [comment]
For bizarre reason, can't pick speaker if I have podcast playing or nothing playing. putting a song to play the devices magically appeared!

> **SOLVED**:
> 
> For some reason, Spotify Connect does not work when playing podcasts! When switching to an actual song, the devices were available again! :laughing:
> 

- https://community.volumio.org/t/solved-spotify-connect-cant-play-this-right-now/6663/2

**Comment by JasonLG1979** [comment]
> For bizarre reason, can't pick speaker if I have podcast playing or nothing playing. putting a song to play the device magically appeared!

That is a known librespot some (possibly most or all?) podcasts are in mp3 format. Librespot only supports vorbis at this time.

**Comment by glensc** [comment]
duplicate: https://github.com/dtcooper/raspotify/issues/253

**Comment by glensc** [comment]
This switch to a song workaround needs to be put to wiki or readme.

**Comment by JasonLG1979** [comment]
> This switch to a song workaround needs to be put to wiki or readme.

What do you mean. Do you mean that you can play a podcast after you initially play a song?

**Comment by glensc** [comment]
audio codec can't be an issue, as I can:
1. put a song to play
2. connect to librespot device
3. switch to podcast

but this won't work:
1. put podcast to play
2. connect to librespot device

**Comment by glensc** [comment]
media I tested with:
- https://open.spotify.com/episode/25hQtnUyDNkxZWjPYCnSk8?si=feU8EvkdSnmK_M7DrQsbAw
- https://open.spotify.com/track/62QohZz1aZNS0ZyAv1v6E4?si=4a324293850741c1

**Comment by glensc** [comment]
as I see it, it affects only the first song played once librespot starts up. I can play, pause whatever I want once I've connected once.

but my experience is limited to under 24 hours of use of this software ;)

**Comment by glensc** [comment]
@JasonLG1979 
1. i am using premium
2. there's no logs to provide. as nothing is happening if it's not unavailable to control state
3. the software is working perfectly in the docker container. no support needed

in any case, putting a song to play workaround just works.

after restart (or start) of the program, spotify is in "unavailable to control" state if:
1. i am playing a podcast
2. nothing is playing

if it's common problem, and has a very simple fix, it should end up in a wiki troubleshoot section.

**Comment by JasonLG1979** [comment]
I have released a new version.  It will be pushed to the deb repo soon.

https://github.com/dtcooper/raspotify/releases/tag/0.31.1
