### ISSUE TITLE
Main process exits - error 101

### ISSUE THREAD

**Issue by mhfarahmandm** [dtcooper/raspotify#390]
I installed the package on Ubuntu 20.10 desktop 64 bit
but it returns 101 error and exits
Any rules I should follow?

**Comment by dtcooper** [comment]
Expected behaviour. The package is specifically compiled for raspberry pi. Try installing librespot.

**Comment by mhfarahmandm** [comment]
> Expected behaviour. The package is specifically compiled for raspberry pi. Try installing librespot.

Actually it's ubuntu on raspberry pi [(RPI version of ubuntu desktop)](https://ubuntu.com/tutorials/how-to-install-ubuntu-desktop-on-raspberry-pi-4)

----
> but it returns 101 error and exits

also when main process exits.  it restart in a few mins but it stops in connecting step: `[2021-04-28T04:27:16Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-e-1tk7.ap.spotify.com:4070"`

while it is in connecting state it look like this screenshot on spotify mobile
![image](https://user-images.githubusercontent.com/44579251/116348018-89c93d00-a802-11eb-8f1b-12b2236ad272.png)

**Comment by dtcooper** [comment]
Okay, I thought when you said 64 bit you meant amd64. Anyway, do you have / are you using a spotify premium account?
