### ISSUE TITLE
Apply filters to sound output

### ISSUE THREAD

**Issue by kopiro** [dtcooper/raspotify#392]
Do you think is there a way to apply some effects like pitch modulation to the output?

**Comment by JasonLG1979** [comment]
https://github.com/librespot-org/librespot/wiki

You can use the pipe backend and pipe the PCM to whatever you like.

**Comment by JasonLG1979** [comment]
Keep in mind though that whatever you pipe to should do playback in a blocking fashion and should handle whatever buffering is necessary. `librespot` will push to the pipe as fast as it can decode the audio stream to PCM and doesn't do any sort of buffering at all. It's basically `librespot` without an audio backend.
