### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by tonygils** [dtcooper/raspotify#399]
Hi,

when i'll try to install it on docker, i'll get this error. 
I allready someone with the same error in 2019 but i didn't find the solution.

checking whether the C compiler works... no
configure: error: in `/toolchain/alsa-lib-1.0.29':
configure: error: C compiler cannot create executables
See `config.log' for more details
The command '/bin/sh -c curl -O https://www.mirrorservice.org/sites/ftp.alsa-pro                                                                                                             ject.org/pub/lib/alsa-lib-1.0.29.tar.bz2     && tar xvjf alsa-lib-1.0.29.tar.bz2                                                                                                              && cd alsa-lib-1.0.29     && CC=arm-linux-gnueabihf-gcc ./configure --host=arm-                                                                                                             linux-gnueabihf --disable-python         --prefix=/toolchain/rpi-tools/arm-bcm27                                                                                                             08/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot     &                                                                                                             & make -j $(nproc --all) && make install     && cd .. && rm -rf alsa-lib-1.0.29.                                                                                                             tar.bz2 alsa-lib-1.0.29' returned a non-zero code: 77
make: *** [Makefile:9: raspotify_*.deb] Fout 77

**Comment by JasonLG1979** [comment]
Can't reproduce with the current master branch.
