### ISSUE TITLE
if using with openvpn speaker isn't detected

### ISSUE THREAD

**Issue by sudoeste** [dtcooper/raspotify#401]
As soon as I connect to a remote openvpn server with my PI raspotify stops being discoverable. Tried to manually update librespot to 0.2 and the problem still happens

Any way I can for it to stay binded to eth0 instead of tun0?

**Comment by 110101011** [comment]
Fix your routing in your .opvn config, so that the tunnel is only used for specific traffic (search Google 'openvpn specific traffic' and you should find enough info)

**Comment by JasonLG1979** [comment]
This is not a Raspotify issue. You'd be better off asking this in a openvpn of networking forum or some place like that?
