### ISSUE TITLE
Not Discoverable on local wifi - Pi 3

### ISSUE THREAD

**Issue by SimonSchaeferFinReach** [dtcooper/raspotify#41]
Hi,
Im using a rasperry pi 3. 
Unfortunately the pi is not discoverable on my local wifi right out of the box by any device.

I can only discover it once I modify the config file and add my username and password to it. 
This however means that everybody else on my network cannot use raspotify. 

Thanks,
Simon

Logs:

> Nov 11 14:28:15 Sipi systemd[546]: Time has been changed
Nov 11 14:28:15 Sipi systemd[1]: Time has been changed
Nov 11 14:28:15 Sipi systemd[1]: apt-daily.timer: Adding 9h 58min 48.041173s random time.
Nov 11 14:28:15 Sipi systemd[1]: apt-daily-upgrade.timer: Adding 56min 23.982175s random time.
Nov 11 14:29:35 Sipi librespot[856]: INFO:librespot::player: Loading track "Fried Hockey Boogie"
Nov 11 14:29:35 Sipi librespot[856]: INFO:librespot::player: Track "Fried Hockey Boogie" loaded
Nov 11 14:33:47 Sipi librespot[856]: INFO:librespot::player: Loading track "On The Road Again"
Nov 11 14:33:48 Sipi librespot[856]: INFO:librespot::player: Track "On The Road Again" loaded
Nov 11 14:37:14 Sipi librespot[856]: INFO:librespot::player: Loading track "Same All Over"
Nov 11 14:37:15 Sipi librespot[856]: INFO:librespot::player: Track "Same All Over" loaded
Nov 11 14:40:26 Sipi systemd[1]: Started Session c3 of user pi.
Nov 11 14:40:43 Sipi systemd[1]: Started Session c4 of user pi.
Nov 11 14:42:52 Sipi systemd[1]: Starting Cleanup of Temporary Directories...
Nov 11 14:42:52 Sipi systemd[1]: Started Cleanup of Temporary Directories.
Nov 11 14:44:30 Sipi systemd[1]: proc-sys-fs-binfmt_misc.automount: Got automount request for /proc/sys/fs/binfmt_misc, triggered by 939 (find)
Nov 11 14:44:30 Sipi systemd[1]: Mounting Arbitrary Executable File Formats File System...
Nov 11 14:44:30 Sipi systemd[1]: Mounted Arbitrary Executable File Formats File System.
Nov 11 14:52:06 Sipi systemd[1]: Stopping Raspotify...
Nov 11 14:52:06 Sipi systemd[1]: Stopped Raspotify.
Nov 11 14:52:06 Sipi systemd[1]: Starting Raspotify...
Nov 11 14:52:06 Sipi systemd[1]: Started Raspotify.
Nov 11 14:52:06 Sipi librespot[1059]: INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg
Nov 11 14:54:22 Sipi systemd[1]: Stopping Raspotify...
Nov 11 14:54:22 Sipi systemd[1]: Stopped Raspotify.
Nov 11 14:54:47 Sipi systemd[1]: Reloading.
Nov 11 14:54:47 Sipi systemd[1]: Reloading.
Nov 11 14:54:50 Sipi dbus[376]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service'
Nov 11 14:54:50 Sipi systemd[1]: Starting PackageKit Daemon...
Nov 11 14:54:50 Sipi PackageKit: daemon start
Nov 11 14:54:50 Sipi dbus[376]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Nov 11 14:54:50 Sipi systemd[1]: Started PackageKit Daemon.
Nov 11 14:56:18 Sipi systemd[1]: Reloading.
Nov 11 14:56:19 Sipi systemd[1]: Reloading.
Nov 11 14:56:20 Sipi systemd[1]: Starting Raspotify...
Nov 11 14:56:20 Sipi systemd[1]: Started Raspotify.
Nov 11 14:56:20 Sipi librespot[1559]: INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg
Nov 11 14:57:46 Sipi systemd[1]: Stopping Raspotify...
Nov 11 14:57:46 Sipi systemd[1]: Stopped Raspotify.
Nov 11 14:57:46 Sipi systemd[1]: Starting Raspotify...
Nov 11 14:57:46 Sipi systemd[1]: Started Raspotify.
Nov 11 14:57:46 Sipi librespot[1588]: INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg
Nov 11 15:00:01 Sipi systemd[1]: Stopping Raspotify...
Nov 11 15:00:01 Sipi systemd[1]: Stopped Raspotify.
Nov 11 15:00:01 Sipi systemd[1]: Starting Raspotify...
Nov 11 15:00:01 Sipi systemd[1]: Started Raspotify.
Nov 11 15:00:01 Sipi librespot[1625]: INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg
Nov 11 15:05:46 Sipi systemd[1]: Stopping Raspotify...
Nov 11 15:05:46 Sipi systemd[1]: Stopped Raspotify.
Nov 11 15:05:46 Sipi systemd[1]: Starting Raspotify...
Nov 11 15:05:46 Sipi systemd[1]: Started Raspotify.
Nov 11 15:05:46 Sipi librespot[1675]: INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg

**Comment by t0k4rt** [comment]
Hi, 
Raspotify can only be used if you setup it with your credentials. it's not an Airplay player, it's a spotify connect client which means: 
* You can remote control songs played by raspotify through your spotify apps
* Raspotify uses your spotify premium account to directly stream content from spotify server 

Your raspotify setup will only be accessible to  an application that is connected to your premium account. The raspotify server won't be discoverable by any other device connected to your wifi network.

Hope it helps.

**Comment by SimonSchaeferFinReach** [comment]
Hi,
Thanks for the reply. Thought so, but then maybe the readme should be changed, because it says that the service is discoverable on the local wifi, which made me think that its discoverable in spotify too. 

Still I would like to be able to allow multiple people using the Pi. Would it be possible to run multiple daemons on the pi and thus provide multiple login data?

Simon

**Comment by dtcooper** [comment]
It's discoverable in Spotify _iff_ you have Spotify Premium. Do you? I'm happy to update the docs @SimonSchaeferFinReach.

**Comment by SimonSchaeferFinReach** [comment]
I do have Spotify Premium, but its only discoverable once I input my login data in the config file. Which kinda contradicts the "it works right out of the box" statement in the docs, it should mention that you have to alter the config if you want it to work. 

Also do you think it would be possible somehow to setup raspotify for multiple people? For example by running multiple raspotify services?

**Comment by Etuldan** [comment]
Same a SimonSchaeferFinReach, I thought raspotify was working out of the box for Premium users.
For exemple, i wanna install a raspi on my sound speaker.
Anyone in my wifi will be able to play any music, as soon as he is premium.

Also, for family accounts, it's quite useless, as only one account can be registered on raspotify.

Anyway, still a great and working app for single users :)

**Comment by dtcooper** [comment]
@Etuldan, it _does_ work out of the box for Premium users. I confirm it working with the following,

1. Flash Raspbian Stretch Lite image on fresh Pi 3
2. Plug the Pi into router
3. Install using the one liner in the README
4. Log onto wifi network using Macbook
5. Start Spotify with Premium acct on Mac
6. See the device there "raspotify (raspberrypi)"
7. Play to it!

Closing. If you have more problems lemme know!

**Comment by Etuldan** [comment]
@dtcooper 
In my case : 
1. Stretch lite on Pi (B)
2. Plugin into router (ethernet)
3. One liner install
4. Wifi network using Win10 and/or Android
5. Start Spotify premium on Win10/Android
6. No raspotify displayed.

As soon as I set account credentials in the raspotify configuration, the 2 wifi devices see the rPI.

UPnP enabled on router.
May be related to some Apple autodiscovering protocol ?

I'm not reopening, as it seems related to someting external to raspotify ;)

**Comment by radeusgd** [comment]
This may be obvious, but if it doesn't work out of the box, you may want to double-check your firewall settings on the PC and raspberry, because that may block discovery.
