### ISSUE TITLE
Question regarding log entries (Unrecognized option: 'linear-volume', but still works as normal)

### ISSUE THREAD

**Issue by voideater** [dtcooper/raspotify#418]
Could this belongs as an issue over at ``librespot`` itself but since I only got that due to having raspotify installed I'll start here.

raspotify works as intended, but when running ``sudo journalctl -f -n 100`` I see a lot of entries like this;

```
Aug 09 21:59:52 raspberrypi librespot[6005]: error: Unrecognized option: 'linear-volume'
```

Running the latest version installed form (``0.16.0~librespot.v0.1.3-37-g0adb851``)
```
xx@raspberrypi: $ sudo systemctl status raspotify.service 
● raspotify.service - Raspotify
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-08-09 21:50:57 CEST; 10min ago
  Process: 5865 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
  Process: 5866 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
 Main PID: 5867 (librespot)
    Tasks: 3 (limit: 2059)
   CGroup: /system.slice/raspotify.service
           └─5867 /usr/bin/librespot --name raspotify (raspberrypi) --device-type speaker --backend alsa --bitrate 320 --disable-audio-cache --enable-volume-normalisation --volume-ctrl linear --initial-volume 100

Aug 09 21:50:57 raspberrypi systemd[1]: Started Raspotify.
Aug 09 21:50:57 raspberrypi librespot[5867]: [2021-08-09T19:50:57Z INFO  librespot] librespot (raspotify v0.16.0) 0adb851 (2020-12-15). Built on 2020-12-30. Build ID: KLdkAvgt
```

Not critical since things are working but just curious on what causes this? Since the arguments seem to be in compliance with what ``librespot`` expects I don't know what I get these entries in the log.

Edit:
Built from source, which uses ``librespot 0.2.0 68bec41 (Built on 2021-08-09, Build ID: 85lyLSa9)`` and still the same. However, raspotify and librespot works fine, so again, it's just because I'm curious that I ask.

**Comment by JasonLG1979** [comment]
`linear-volume` is a deprecated option.
