### ISSUE TITLE
USB audio output not working

### ISSUE THREAD

**Issue by camilo-r-r** [dtcooper/raspotify#42]
hey everyone,

I can't get raspotify to work with my USB audio interface. The interface is recognized just fine and can play other audio sources, it's just raspotify that doesn't work. when i  run

`sudo systemctl status raspotify`

I get

`Nov 11 16:34:41 raspberrypi librespot[598]: INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg
Nov 11 16:35:15 raspberrypi librespot[598]: INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-mvpz.ap.spotify.com:4070"
Nov 11 16:35:16 raspberrypi librespot[598]: INFO:librespot_core::session: Authenticated as "camilo_rojo" !
Nov 11 16:35:16 raspberrypi librespot[598]: INFO:librespot::audio_backend::alsa: Using alsa sink
Nov 11 16:35:16 raspberrypi librespot[598]: INFO:librespot_core::session: Country: "DE"
Nov 11 16:35:16 raspberrypi librespot[598]: INFO:librespot::player: Loading track "Computer Liebe - 2009 Remastered Version"
Nov 11 16:35:17 raspberrypi librespot[598]: INFO:librespot::player: Track "Computer Liebe - 2009 Remastered Version" loaded
Nov 11 16:35:17 raspberrypi librespot[598]: ALSA lib pcm.c:8382:(snd_pcm_set_params) Sample format not available for PLAYBACK: Invalid argument
Nov 11 16:35:17 raspberrypi librespot[598]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs
Nov 11 16:35:17 raspberrypi librespot[598]: note: Run with `RUST_BACKTRACE=1` for a backtrace.`

here is what my settings look like 

`# /etc/default/raspotify -- Arguments for librespot

# Device name on Spotify Connect
DEVICE_NAME="M-AUDIO"
OPTIONS="--device hw:1,0"
# Bitrate, one of 96 (low quality), 160 (default quality), or 320 (high quality)
#BITRATE="160"

# Additional command line arguments for librespot can be set below.
# See `librespot -h` for more info.
#
# To make your device visible on Spotify Connect across the Internet add your
# username and password which can be set via "Set device password", on your
# account settings, use `--username` and `--password`.
#
# To choose a different output device (ie a USB audio dongle or HDMI audio out),
# use `--device` with something like `--device hw:0,1`. Your mileage may vary.
#
#OPTIONS="--device hw:1,0"
`

also, in case it helps, if i run aplay -l I get: 

`**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: M2X2 [M-Track 2X2], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0` 

The error output says that the sample format is not available for playback, what should i change then? 
Thanks a lot in advance!

**Comment by audiogeek123** [comment]
Hello, maybe you can find an answer here: #40
