### ISSUE TITLE
Inclusion of Librespot build options for

### ISSUE THREAD

**Issue by mactzu** [dtcooper/raspotify#421]
Can i firstly say thank you, 

This implementation is great.  THe issue that i have where i require the pulseaudio backend built into the librespot. 

It seems the installer basic create package directly from github so i modify the build on cloned git for example  it wont read.

Would it be possible to options for the build o librespot into script ? 

or if there is another clever for me to make the changes, please let me know.

**Comment by JasonLG1979** [comment]
No. Raspotify will be alsa only for the foreseeable future.

You can compile librespot on your pi by following the instructions at the librespot repo.
