### ISSUE TITLE
Lower the volume of the stream (not the device) temporarily (or pause the stream)?

### ISSUE THREAD

**Issue by bitdawg** [dtcooper/raspotify#423]
Is there a way to lower the volume of the stream temporarily (or as a defined on/off action), or a way to pause the stream, from the commandline/api/script?  I imagine if this was available it's a librespot function.

What I'm looking for is simultaneously playback from the RPI but to have the spotify connect playback volume reduced or paused while other playback is happening and then resume (at normal volume).

**Comment by dtcooper** [comment]
You could try Spotify's web API.
