### ISSUE TITLE
Can select device, but no sound plays

### ISSUE THREAD

**Issue by mferuscomelo** [dtcooper/raspotify#428]
I'm trying to set up a Bluetooth speaker to stream Spotify. Everything works perfectly when playing music through the headphone jack, though the problems arise when trying to play using a Bluetooth speaker. 

I've successfully managed to pair the device through the Bluetooth Panel and playing music on Youtube works as expected through the Bluetooth speaker. The speaker also works when executing `speaker-test -c2 -twav -l7 -D default` and `speaker-test -c2 -twav -l7 -D pulse` in the terminal. 

I have also followed [these](https://github.com/dtcooper/raspotify#play-via-bluetooth-speaker-on-raspberry-pi-desktop) instructions on the Raspotify GitHub page to play through a Bluetooth speaker on Raspberry Pi Desktop to no avail. I have also tried editing `.config/systemd/user/raspotify.service` by adding `--device default` or `--device pulse` to `ExecStart` making sure to run `sudo systemctl daemon-reload` and `sudo systemctl restart raspotify` after each attempt.

Trying [these](https://github.com/dtcooper/raspotify#play-via-bluetooth-speaker-without-raspberry-pi-desktop) instructions to play through a Bluetooth speaker without Raspberry Pi Desktop haven't helped either, even with `--device default` or `--device pulse` in `ExecStart`

Unfortunately, I haven't been able to get it to work. Am I doing something wrong?

**Comment by araucarialab** [comment]
I was having the same problem, see issue [#408 ](https://github.com/dtcooper/raspotify/issues/408)
When modifying OPTIONS="--device hw:0,0", the first number is the **card** and the second one is the **device**.
