### ISSUE TITLE
Feature Request... Docker?

### ISSUE THREAD

**Issue by spencerthayer** [dtcooper/raspotify#431]
It would be super cool if we could set up all the configurations for raspotify with a docker-compose file and run it without having to do all that extra stuff. Is that something worth considering? Thanks!

**Comment by JasonLG1979** [comment]
Out of scope. You can checkout [this comment](https://github.com/dtcooper/raspotify/issues/442#issuecomment-970216095) for a link to a librespot docker image by another user.
