### ISSUE TITLE
librespot panic as a result of Pulseaudio problem

### ISSUE THREAD

**Issue by bennypr0fane** [dtcooper/raspotify#439]
I run Raspotify on my Raspberry Pi. The log is all lLibrespot messages, so I thought this would be the right place to report:

```
pi@raspberrypi:~ $ service raspotify status
● raspotify.service - Raspotify
Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
Active: active (running) since Thu 2021-11-04 00:12:35 CET; 36min ago
Process: 1227 ExecStartPre=/bin/mkdir -m 0755 -p /var/cache/raspotify (code=exited, status=0/SUCCESS)
Process: 1228 ExecStartPre=/bin/chown raspotify:raspotify /var/cache/raspotify (code=exited, status=0/SUCCESS)
Main PID: 1229 (librespot)
Tasks: 2 (limit: 4915)
CGroup: /system.slice/raspotify.service
└─1229 /usr/bin/librespot --name raspotify (raspberrypi) --device-type speaker --backend alsa --bitrate 160 --disable-audio-cache --enable-volume-normalisation --volume-ctrl linear --initial-volume 100

Nov 04 00:18:14 raspberrypi librespot[1229]: 17: 0x54b304 - <librespot_playback::player::PlayerInternal as futures::future::Future>::poll::he6e04a5bccf94e34
Nov 04 00:18:14 raspberrypi librespot[1229]: 18: 0x4af300 - futures::task_impl::std::set::hab1c1811473e3998
Nov 04 00:18:14 raspberrypi librespot[1229]: 19: 0x4a5838 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8286c5a0fd04a387
Nov 04 00:18:14 raspberrypi librespot[1229]: 20: 0x4c04f4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h76e6c7604d7daced
Nov 04 00:18:14 raspberrypi librespot[1229]: 21: 0x8ec940 - <alloc::boxed::Box as core::ops::function::FnOnce>::call_once::h6b7ad05f87ff90ae
Nov 04 00:18:14 raspberrypi librespot[1229]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
Nov 04 00:18:14 raspberrypi librespot[1229]: 22: 0x8ec940 - <alloc::boxed::Box as core::ops::function::FnOnce>::call_once::he9130e675b8d97ee
Nov 04 00:18:14 raspberrypi librespot[1229]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
Nov 04 00:18:14 raspberrypi librespot[1229]: 23: 0x8ec940 - std::sys::unix:thread:Thread:new:thread_start::h7a3f6590d8e03e95
Nov 04 00:18:14 raspberrypi librespot[1229]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
```

Here's the last part of the daemon log:

    lines 456-515/515 (END)
    Nov 04 00:50:31 raspberrypi librespot[2396]: [2021-11-03T23:50:31Z INFO librespot_core::session] Connecting to AP "gew1-accesspoint-a-7kvp.ap.spotify.com:4070"
    Nov 04 00:50:36 raspberrypi librespot[2396]: [2021-11-03T23:50:36Z INFO librespot_core::session] Authenticated as "c8gc9tpfjfbjov02yhbylpmr9" !
    Nov 04 00:50:36 raspberrypi librespot[2396]: [2021-11-03T23:50:36Z INFO librespot_playback::audio_backend::alsa] Using alsa sink
    Nov 04 00:50:36 raspberrypi librespot[2396]: [2021-11-03T23:50:36Z INFO librespot_core::session] Country: "AT"
    Nov 04 00:50:39 raspberrypi librespot[2396]: [2021-11-03T23:50:39Z INFO librespot_playback::player] Loading with Spotify URI spotify:track:6asvrBtFidBQxVtxMW18MG
    Nov 04 00:50:39 raspberrypi librespot[2396]: [2021-11-03T23:50:39Z INFO librespot_playback::player] (375986 ms) loaded
    Nov 04 00:50:40 raspberrypi librespot[2396]: ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Access denied
    Nov 04 00:50:40 raspberrypi librespot[2396]: [2021-11-03T23:50:40Z ERROR librespot_playback::audio_backend::alsa] Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ECONNREFUSED: Connection refused'
    Nov 04 00:50:40 raspberrypi librespot[2396]: [2021-11-03T23:50:40Z ERROR librespot_playback::player] Could not start audio: Alsa error: PCM open failed
    Nov 04 00:50:40 raspberrypi librespot[2396]: ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Access denied
    Nov 04 00:50:40 raspberrypi librespot[2396]: [2021-11-03T23:50:40Z ERROR librespot_playback::audio_backend::alsa] Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ECONNREFUSED: Connection refused'
    Nov 04 00:50:40 raspberrypi librespot[2396]: [2021-11-03T23:50:40Z ERROR librespot_playback::player] Could not start audio: Alsa error: PCM open failed
    Nov 04 00:50:40 raspberrypi librespot[2396]: ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Access denied
    Nov 04 00:50:40 raspberrypi librespot[2396]: [2021-11-03T23:50:40Z ERROR librespot_playback::audio_backend::alsa] Alsa error PCM open ALSA function 'snd_pcm_open' failed with error 'ECONNREFUSED: Connection refused'
    Nov 04 00:50:40 raspberrypi librespot[2396]: [2021-11-03T23:50:40Z ERROR librespot_playback::player] Could not start audio: Alsa error: PCM open failed
    Nov 04 00:50:40 raspberrypi librespot[2396]: thread '' panicked at 'called Option::unwrap() on a None value', playback/src/audio_backend/alsa.rs:138:45
    Nov 04 00:50:40 raspberrypi librespot[2396]: stack backtrace:
    Nov 04 00:50:40 raspberrypi librespot[2396]: 0: 0x88a278 - std::backtrace_rs::backtrace::libunwind::trace::h9c6af82ecb947420
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
    Nov 04 00:50:40 raspberrypi librespot[2396]: 1: 0x88a278 - std::backtrace_rs::backtrace::trace_unsynchronized::h80561bf66e637b12
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
    Nov 04 00:50:40 raspberrypi librespot[2396]: 2: 0x88a278 - std::sys_common::backtrace::_print_fmt::h8904fddc87bf6b5e
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
    Nov 04 00:50:40 raspberrypi librespot[2396]: 3: 0x88a278 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc883ceb7a13219f2
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
    Nov 04 00:50:40 raspberrypi librespot[2396]: 4: 0x8b2290 - core::fmt::write::ha75209c8e86bef45
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
    Nov 04 00:50:40 raspberrypi librespot[2396]: 5: 0x882e18 - std::io::Write::write_fmt::h4cce8be81a41c537
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
    Nov 04 00:50:40 raspberrypi librespot[2396]: 6: 0x88d1c0 - std::sys_common::backtrace::_print::hdc9e28891c09ab0b
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
    Nov 04 00:50:40 raspberrypi librespot[2396]: 7: 0x88d1c0 - std::sys_common::backtrace::print::h85895381379b4dc1
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
    Nov 04 00:50:40 raspberrypi librespot[2396]: 8: 0x88d1c0 - std::panicking::default_hook::{{closure}}::h6b4de484f2428118
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
    Nov 04 00:50:40 raspberrypi librespot[2396]: 9: 0x88cdbc - std::panicking::default_hook::h3966366a200b03f1
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
    Nov 04 00:50:40 raspberrypi librespot[2396]: 10: 0x88d910 - std::panicking::rust_panic_with_hook::h068b5368b0949ced
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
    Nov 04 00:50:40 raspberrypi librespot[2396]: 11: 0x88d4c4 - std::panicking::begin_panic_handler::{{closure}}::hde463ebfc6f96538
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
    Nov 04 00:50:40 raspberrypi librespot[2396]: 12: 0x88a7f8 - std::sys_common::backtrace::__rust_end_short_backtrace::hb945924c40726c97
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
    Nov 04 00:50:40 raspberrypi librespot[2396]: 13: 0x88d47c - rust_begin_unwind
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
    Nov 04 00:50:40 raspberrypi librespot[2396]: 14: 0x8af960 - core::panicking::panic_fmt::h27b19d6e6dedd33e
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
    Nov 04 00:50:40 raspberrypi librespot[2396]: 15: 0x8af8bc - core::panicking::panic::h2a6f9b05d102de10
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
    Nov 04 00:50:40 raspberrypi librespot[2396]: 16: 0x516020 - <librespot_playback::audio_backend::alsa::AlsaSink as librespot_playback::audio_backend::Sink>::write::hfb124b87fed1cc15
    Nov 04 00:50:40 raspberrypi librespot[2396]: 17: 0x4f3304 - <librespot_playback::player::PlayerInternal as futures::future::Future>::poll::he6e04a5bccf94e34
    Nov 04 00:50:40 raspberrypi librespot[2396]: 18: 0x457300 - futures::task_impl::std::set::hab1c1811473e3998
    Nov 04 00:50:40 raspberrypi librespot[2396]: 19: 0x44d838 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8286c5a0fd04a387
    Nov 04 00:50:40 raspberrypi librespot[2396]: 20: 0x4684f4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h76e6c7604d7daced
    Nov 04 00:50:40 raspberrypi librespot[2396]: 21: 0x894940 - <alloc::boxed::Box as core::ops::function::FnOnce>::call_once::h6b7ad05f87ff90ae
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
    Nov 04 00:50:40 raspberrypi librespot[2396]: 22: 0x894940 - <alloc::boxed::Box as core::ops::function::FnOnce>::call_once::he9130e675b8d97ee
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
    Nov 04 00:50:40 raspberrypi librespot[2396]: 23: 0x894940 - std::sys::unix:thread:Thread:new:thread_start::h7a3f6590d8e03e95
    Nov 04 00:50:40 raspberrypi librespot[2396]: at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87

Any idea why Librespot would be deneid access here?

    Nov 04 00:50:40 raspberrypi librespot[2396]: ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Access denied

**Comment by JasonLG1979** [comment]
Raspotify is primarily intended to be used in a headless enviroment (Raspberry Pi OS lite) For desktop versions of Raspberry Pi OS [spotifyd](https://spotifyd.github.io/spotifyd/installation/Raspberry-Pi.html) offers similar functionality, much better PulseAudio compatibility and is a better choice.
