### ISSUE TITLE
Raspotify doesn't work properly with usb audio without Pulseaudio

### ISSUE THREAD

**Issue by SirJohnDoe** [dtcooper/raspotify#44]
My USB DAC doesn't work properly unless I use the "--plug hw:1,0" option ("--device hw:1,0), otherwise I'd get the following error:

`ALSA lib pcm.c:7918:(snd_pcm_set_params) Sample format not available for PLAYBACK: Invalid argument
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:329
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:859`

The USB DAC is set as the default audio output and works with any other program, just not with raspotify/librespot by default. Just now I discovered that simply by installing pulseaudio this issue disappears. The backend used by librespot is still ALSA, but I don't have to do "plughw" or anything of the sort. Perhaps this can be added to the README for other people facing this issue.

**Comment by maskov1** [comment]
I have been using raspotify on DietPi on two RPis, one connected to Grace M9XX, and the other one to Schiit Modi Multibit. All good for a month and then suddenly Grace started failing on playback. The only thing which resolved it for me was installing pulseaudio.
