### ISSUE TITLE
Raspotify working with new release of Raspberry OS?

### ISSUE THREAD

**Issue by DaMuhr** [dtcooper/raspotify#446]
Hey there,
was just wondering if the Raspotify service already works for the new version of raspberry OS, Bullseye. I upgraded today and raspotify isn't working now.
To give a little context:
If I check the status of the raspotify app with `sudo systemctl status raspotify` it shows that it's active and running but it doesn't play sound and disconnects instantly if I try to change the volume. With SOX I can play test sounds just fine.
Any help would be appreciated.

**Comment by aleksa3123** [comment]
I have sam issue, but I was thinking that my Hifiberry digi driver is bugging the shit out of it. You can see my status output

**Comment by JasonLG1979** [comment]
LIbrespot works great on Raspberry Pi OS Bullseye if you compile it yourself but Raspotify maybe not so much judging from bug reports.

@dtcooper is looking for someone to [take over maintanership](https://github.com/dtcooper/raspotify/issues/300#issuecomment-966696609) see the top of the README.md:

> warning NOTE: I have limited to no time to work on this package these days!

> I am looking for a maintainer to help with issues and updating the package. Please reach out via email at david@jew.pizza if > you have interest in helping.

> Cheers,

> David

I'm no docker expert by any means but I would say that the docker file could be updated to Bullseye (it's currently stretch) and some deprecated option names need to be dealt with and it should be good.

In the mean time it's really easy to build librespot yourself on your raspberry pi and just replace the librespot binary that ships with raspotify.

**Comment by JasonLG1979** [comment]
Update: I have a PR in that updates raspotify and I have volunteered to help @dtcooper maintain raspotify. Just waiting for him to get back to me.

**Comment by dtcooper** [comment]
@JasonLG1979 I've added you as a maintainer.

**Comment by dtcooper** [comment]
> I'm no docker expert by any means but I would say that the docker file could be updated to Bullseye (it's currently stretch) and some deprecated option names need to be dealt with and it should be good.

Me neither! :)

**Comment by JasonLG1979** [comment]
A new release is on the way. I'm going to close this.
