### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by MrYom17** [dtcooper/raspotify#45]
Hi,

How could I read out metadata from raspotify ? (artist name etc)
I'd like display them on a hd44780

thanks

**Comment by silberjan** [comment]
Similar request here: 
I want to call a webhook (to slack) everytime the song changes. It should post the song and artist to our #nowplaying slack channel.

Any idea how to extract this kind of information?

**Comment by dtcooper** [comment]
@silberjan + @MrYom17: Have you tried polling [Spotify's Web API](https://developer.spotify.com/web-api/)?

**Comment by silberjan** [comment]
i would call the `audio-analysis` endpoint if there is a way to get the currently playing songs id from raspotify (librespot)

**Comment by dtcooper** [comment]
@MrYom17 you can either try the Web API or follow the instructions I laid out in #55 and use one of the forks mentioned there to track metadata changes. Thanks!
