### ISSUE TITLE
command line options/args to send 'next track'' command possible?

### ISSUE THREAD

**Issue by jakka351** [dtcooper/raspotify#464]
Hi I have got raspotify on a PI in my car, I want to hook up to my canbus steering wheel controls - I have the button presses available as key presses or a command or anything really. Any options here?

**Comment by JasonLG1979** [comment]
No. You would need to roll your own control interface by connecting to Spotify's web api.

**Comment by jakka351** [comment]
For anyone that comes looking with similar question - I have hacked together this monster https://github.com/jakka351/Rpotify and have canbus steering wheel controls controlling raspotify on a RPI4 playing wirelessly from my phone.

**Comment by JasonLG1979** [comment]
You could add a page to the wiki?

**Comment by jakka351** [comment]
I will write something up

**Comment by JasonLG1979** [comment]
Maybe page in the wiki with a list of links to projects that use Raspotify along with a very brief description of the project?

**Comment by JasonLG1979** [comment]
@jakka351 Done:

https://github.com/dtcooper/raspotify/wiki/Projects-related-to-Raspotify

**Comment by jakka351** [comment]
Cool.
