### ISSUE TITLE
raspotify service continuesly restarting: librespot status=217/USER

### ISSUE THREAD

**Issue by bubble1999** [dtcooper/raspotify#471]
Hello,

first I want to say thankyou for this great project! I used to use it since quite a while.
However, I installed raspotify recently on a newly set up RaspberryPi 3B running a fresh installed OSMC (18.9.122-2-osmc LEIA, running on debian 10 buster).
The same hardware used to work before the new OSMC install.

After installing Raspotify (0.31.3~librespot.v0.3.1-19-gbbd575e) and checking service status I get this message:
` sudo systemctl status raspotify
* raspotify.service - Raspotify (Spotify Connect Client)
   Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-12-02 10:22:58 CET; 2s ago
     Docs: https://github.com/dtcooper/raspotify
           https://github.com/librespot-org/librespot
           https://github.com/dtcooper/raspotify/wiki
           https://github.com/librespot-org/librespot/wiki/Options
  Process: 29777 ExecStart=/usr/bin/librespot --name ${DEVICE_NAME} --device-type ${DEVICE_TYPE} $BACKEND_ARGS --bitrate ${BITRATE} $CACHE_ARGS $VOLUME_ARGS $OPTIONS (code=exited, status=217/USER)
 Main PID: 29777 (code=exited, status=217/USER)
`

 journalctl -u raspotify shows such kind of messages every 10 seconds:
`Dec 01 13:10:13 osmc systemd[1]: raspotify.service: Service RestartSec=10s expired, scheduling restart.
Dec 01 13:10:13 osmc systemd[1]: raspotify.service: Scheduled restart job, restart counter is at 755.
Dec 01 13:10:13 osmc systemd[1]: Stopped Raspotify (Spotify Connect Client).
Dec 01 13:10:13 osmc systemd[1]: Started Raspotify (Spotify Connect Client).
Dec 01 13:10:13 osmc systemd[21512]: raspotify.service: Failed to set up user namespacing: Invalid argument
Dec 01 13:10:13 osmc systemd[21512]: raspotify.service: Failed at step USER spawning /usr/bin/librespot: Invalid argument
Dec 01 13:10:14 osmc systemd[1]: raspotify.service: Main process exited, code=exited, status=217/USER
Dec 01 13:10:14 osmc systemd[1]: raspotify.service: Failed with result 'exit-code'.
`

Manually installing raspotify version 0.16.0 works fine.

If you need more information, please let me know. 

Best regards,
Andreas

**Comment by JasonLG1979** [comment]
OSMC is not a supported OS. That particular error seems to be because the Raspotify service is trying to used a systemd feature that is not supported yet in Debian 10. You would probably have better luck with a distro based on a current Debian version.
