### ISSUE TITLE
Play pause next previous with Bluetooth

### ISSUE THREAD

**Issue by GTHeyyy** [dtcooper/raspotify#473]
media controls do not work with Raspotify bluetooth connection (headless).
My speaker has play, pause, next and previous buttons which work smoothly with any Android phone (bluetooth connection). I cannot use them with rapsotify on my Raspberry 4

Any way to solve this?

Raspberry Pi 4
Version: 0.31.3
Bluetooth connection via pi-btaudio (https://github.com/bablokb/pi-btaudio)

**Comment by JasonLG1979** [comment]
Why would you expect them to? You would need to wire bluetooth up to the Spotify web api. That is way out of scope of Raspotify. Raspotify is just a packaged version of librespot.
