### ISSUE TITLE
No Config File visible

### ISSUE THREAD

**Issue by weinbrand** [dtcooper/raspotify#484]
### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Latest Version

- [X] I'm running the latest version of Raspotify

### Due Diligence

- [X] I have done my due diligence

### What happened?

I have setup a brand new PiZero with up to date Raspbian Lite (Bullseye). I have installed all available updates. I have installed latest version of Raspotify. Unfortunately the config file /etc/default/raspotify does not exist.

I checked the other issues. There it was either a problem with the version of raspbian or a non-yet-published version of raspotify. From what I see and understand it has now been published, so the automated way to install should work (as described in the readme).

Any advice/support?

Many thanks,
Christian

OS:
`pi@spotillon:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

**Comment by JasonLG1979** [comment]
https://github.com/dtcooper/raspotify/wiki/Configuration

https://github.com/dtcooper/raspotify/wiki/Migration-from-older-versions-to-0.31.4-and-beyond
