### ISSUE TITLE
Alternatives to bluealsa in bullseye

### ISSUE THREAD

**Issue by spippoli** [dtcooper/raspotify#490]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Hello,
I'm using raspotify on a headless raspberry pi zero  sending the audio to a bluetooth speaker. It was working fine on buster but now I upgraded to bullseye and it is broken. 
The problem seems to be that bluealsa is not available on bullseye, so I made a desperate attempt to install it anyway from buster repositories but I can't get it to work (both by itself or via pi-btaudio) as I'm getting different flavors of 
`Audio Sink Error Connection Refused: <AlsaSink> Device bluealsa May be Invalid, Busy, or Already in Use`

So my question is: is there an alternative to bluealsa to get a working bluetooth alsa device?

**Comment by JasonLG1979** [comment]
That doesn't have anything to do with Raspotify.
