### ISSUE TITLE
Can see and connect but no sound.

### ISSUE THREAD

**Issue by Bazmundi** [dtcooper/raspotify#494]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

I have installed raspotify onto RPi 3B+ running linux 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l

Spotify on my Windows 10 laptop "sees" the raspotify on the network, and can connect.  

I am not using proxies etc.

I have a premium Spotify account etc.  I have setup my spotify username and password in /etc/raspotify/conf.

I have used defaults everywhere else in /etc/raspotify/conf.

I have tried restart, stop/start and reboot etc.

I am using the RCA audio out (not USB and not HDMI).  I have used raspi-config to set audio to the audio jack.  I also went into alsamixer to switch to headphones - but that seems to switch back to HDMI when I go back in?   I assume that is just setting parameters for the different modes?  So, the volume has been pumped up for headphones under alsamixer.

There did not seem to be a requirement for a sound card?  

So, it seems there may need be something else in the conf file I need setup?   

```
$ cat /proc/asound/modules
 0 snd_bcm2835
 1 snd_bcm2835
```

So `sudo speaker-test -c2 -twav -l7 -D plughw:1,0` successfully sends test audio to left/right speakers.   Whereas `sudo speaker-test -c2 -twav -l7 -D plughw:0,0` does not?  So, audio seems to be going to RCA cable and so cable seems fine.

**Comment by JasonLG1979** [comment]
The wiki has a [Troubleshooting page](https://github.com/dtcooper/raspotify/wiki/Troubleshooting) that explains how to set the default audio device.

**Comment by Bazmundi** [comment]
> This question or issue can probably be easily answered or resolved by reading the docs/wiki.

If you pay attention to the information I supplied the evidence is I did use the info at the troubleshooting page.   It directs one to use alsamixer to increase volume, which I indicated I did.  It suggests a means of checking audio is working over the RCA, which I indicated I did.  I indicated that I was not using USB sound so none of the USB sound options appeared relevant.  I am not using pulse audio nor bluetooth.

So, there is actually nothing in the wiki or troubleshooting that does help.

**Comment by JasonLG1979** [comment]
> If you pay attention to the information I supplied the evidence is I did use the info at the troubleshooting page.

That kind of attitude will get you nowhere. I paid plenty of attention and nothing you said was really that relevant other than `hw:0` is HDMI and `hw:1` is analog out. I will say it again. The wiki has the info you need to set the analog out as your default.

**Comment by JasonLG1979** [comment]
I bet if you followed the wiki, edited `/etc/asound.conf` and added:

```
defaults.ctl.card 1
defaults.pcm.card 1
```

Things would work as you'd expect. But I don't know I'm not really paying attention...

**Comment by Bazmundi** [comment]
> I bet if you followed the wiki, edited `/etc/asound.conf` and added:
> 
> ```
> defaults.ctl.card 1
> defaults.pcm.card 1
> ```
> 
> Things would work as you'd expect. But I don't know I'm not really paying attention...

Ah, so ignore the fact that that guidance was directed at people who where trying to setup the USB sound.  Gotcha.

**Comment by JasonLG1979** [comment]
> Ah, so ignore the fact that that guidance was directed at people who where trying to setup the USB sound. Gotcha.

The wiki presents some common questions and answers. I can only present the information to you. I can not understand it for you. Maybe more extrapolation and less attitude.
