### ISSUE TITLE
Update wiki article for Bullseye packet issues

### ISSUE THREAD

**Issue by BlackYps** [dtcooper/raspotify#496]
### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Latest Version

- [X] I'm running the latest version of Raspotify

### Due Diligence

- [X] I have done my due diligence

### What happened?

bluealsa is not available in the repositories of Bullseye. At least in the Light version that I use. This should be mentioned in this wiki article in the [headless section](https://github.com/dtcooper/raspotify/wiki/Play-via-Bluetooth-Speaker-on-Raspberry-Pi-Desktop#play-via-bluetooth-speaker-without-raspberry-pi-desktop). For the same reason pi-btaudio is unusable at the moment because its install fails. This should also be mentioned. See the issue here: https://github.com/bablokb/pi-btaudio/issues/8

**Comment by JasonLG1979** [comment]
The wiki is editable. You don't need to file a bug report to update it.

**Comment by BlackYps** [comment]
Oh, I didn't even realize
