### ISSUE TITLE
Trouble accessing raspotify config

### ISSUE THREAD

**Issue by Sjakkie** [dtcooper/raspotify#503]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Hi, 

I installed  raspotify as described on this githup page (the easy method). Raspotify is discovered by my mobile device. But I have no sound. I seem to remeber that I have to make changes to the raspotify config file. But when i go to the location /etc/raspotify I get the message that access is denied.

What am i doing wrong?

Tnx in advance,
Sjak

**Comment by JasonLG1979** [comment]
You must have root/admin privileges to see the content of the folder.
