### ISSUE TITLE
Set External Audio Card as Default Output Device

### ISSUE THREAD

**Issue by miibrito92** [dtcooper/raspotify#506]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Last time I configured Raspotify it was not in the latest version and now I just can't figure out how to set this up. I tried to follow suggestions and all led to the old app and to be truthfull, I'm not that expert about this.
Before I wrote something like this "OPTIONS="--device hw:2,0" and that worked. Now already tried messing with the 
LIBRESPOT_MIXER="alsa"
LIBRESPOT_ALSA_MIXER_DEVICE="--device"
LIBRESPOT_DEVICE="--device hw:2,0" (or) "hw:CARD=T6,DEV=0"

When using "librespot --device ?" the sound card won't show up.

Any help? Thanks

**Comment by JasonLG1979** [comment]
What does `aplay -L` and `aplay -l` say?

**Comment by JasonLG1979** [comment]
If `"OPTIONS="--device hw:2,0"` worked in the past then it should be `LIBRESPOT_DEVICE="hw:2,0"`.
