### ISSUE TITLE
Requires Spotify Premium

### ISSUE THREAD

**Issue by galorin** [dtcooper/raspotify#53]
While I don't mind this, there should be a notice for it in the Readme.

**Comment by mmarcm** [comment]
There is already a notice: "Raspotify works on a Raspberry Pi running Raspbian. You'll need a Spotify Premium account in order to use Connect."
😄

**Comment by dtcooper** [comment]
Hi @galorin,

Please see the [introduction](https://github.com/dtcooper/raspotify#introduction) section of the readme. 💃 

Closing.
