### ISSUE TITLE
Does Raspotify require a Spotify premium account?

### ISSUE THREAD

**Issue by cclockworks** [dtcooper/raspotify#562]
### Due Diligence

- [x] I have done my due diligence

### What can we help you with?

Hello, I use a free Spotify account and I am interested in using Raspotify. However I am unsure if I require a Spotify premium account to use it. Thank you!

**Comment by JasonLG1979** [comment]
Yes. Raspotify (librespot under the hood) requires a premium account.

**Comment by dtcooper** [comment]
@JasonLG1979 think we should update the readme to contain a quick blurb about that?

**Comment by JasonLG1979** [comment]
Sure. I can do that tonight after work.

**Comment by JasonLG1979** [comment]
@dtcooper Done:
https://github.com/dtcooper/raspotify/commit/e0072a442d95998a2ea398d73f818d2c6acc36b0
