### ISSUE TITLE
Can raspotify be off on bootup?

### ISSUE THREAD

**Issue by gseastream** [dtcooper/raspotify#61]
Is there a way to have raspotify be off by default when the Pi is turned on? And then I can issue a command or something to start it up and turn on Spotify Connect? This is only to keep the device off of spotify if that's not what I'm using the Pi for at the moment.

**Comment by dtcooper** [comment]
Of course. It uses `systemd` to run. Try

```
sudo system COMMAND raspotify
```

Where `COMMAND` is one of:

* `disable` to disable at boot,
* `enable` to (re-)enable at boot,
* `start` to start the service if stopped or disabled; and
* `stop` to stop the service if running or enabled.

Hope that helps! Let me know if you have any other issues. Closing!
