### ISSUE TITLE
Raspberry Pi 3 - GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by s-juozaitis** [dtcooper/raspotify#616]
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Are you sure?

- [X] I'm not trying to run Raspotify on a ARMv6 device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Compatible Configuration

- [X] I'm running Raspotify on a compatible Configuration

### Latest Version

- [X] I'm running the latest version of Raspotify

### Are you sure?

- [X] I'm not running Raspotify 0.31.8.1 on a on a Pi v1 or Pi Zero

### Due Diligence

- [X] I have done my due diligence

### What happened?

Hello,

I'm trying to install Raspotify on Raspberry Pi 3:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

By running the installation command I received following error:
libc6 >= 2.31 is required but 2.28-10+rpt2+rpi1+deb10u1 is installed.
coreutils >= 8.32 is required but 8.30-3 is installed.
systemd >= 247.3 is required but 241-7~deb10u8+rpi1 is installed.
libasound2 >= 1.2.4 is required but 1.1.8-1+rpt2 is installed.
alsa-utils >= 1.2.4 is required but 1.1.8-2+rpt1 is installed.
libpulse0 >= 14.2 is required but 12.2-4+deb10u1+rpt3 is installed.

Please make sure you are running a compatible armhf (ARMv7), arm64, or amd64 Debian based OS.

I tried to install package from .deb file but still receive incompatible package list.

### Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )

```shell
root@acoustic-energy:/opt# sudo apt-get -y install curl && curl -sL https://dtcooper.github.io/raspotify/install.sh | sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Unmet minimum required package version(s):

libc6 >= 2.31 is required but 2.28-10+rpt2+rpi1+deb10u1 is installed.
coreutils >= 8.32 is required but 8.30-3 is installed.
systemd >= 247.3 is required but 241-7~deb10u8+rpi1 is installed.
libasound2 >= 1.2.4 is required but 1.1.8-1+rpt2 is installed.
alsa-utils >= 1.2.4 is required but 1.1.8-2+rpt1 is installed.
libpulse0 >= 14.2 is required but 12.2-4+deb10u1+rpt3 is installed.

Please make sure you are running a compatible armhf (ARMv7), arm64, or amd64 Debian based OS.
```

**Comment by JasonLG1979** [comment]
Duplicate of https://github.com/dtcooper/raspotify/issues/565, https://github.com/dtcooper/raspotify/issues/564, https://github.com/dtcooper/raspotify/issues/511, https://github.com/dtcooper/raspotify/discussions/588, and https://github.com/dtcooper/raspotify/issues/590.
