### ISSUE TITLE
Spotify Windows and Web Client do not highlight currently playing song in playlist viewer

### ISSUE THREAD

**Issue by fre4242** [dtcooper/raspotify#618]
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Are you sure?

- [X] I'm not trying to run Raspotify on a ARMv6 device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Compatible Configuration

- [X] I'm running Raspotify on a compatible Configuration

### Latest Version

- [X] I'm running the latest version of Raspotify

### Are you sure?

- [X] I'm not running Raspotify 0.31.8.1 on a Pi v1 or Pi Zero

### Due Diligence

- [X] I have done my due diligence

### What happened?

The Spotify Windows and web client do not highlight currently playing song in playlist viewer when this song is played by raspotify connect client.
It works for the Android spotify client while raspotify is playing. This client shows the currently playing song while the windows and web clients do not.
When making the desktop client connect to any other official spotify client (like Android) then it highlights the currently playing song, only when connected to raspotify it doesn't.

### Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )

```shell
do not have one
```

**Comment by JasonLG1979** [comment]
This is a known upstream issue with librespot. That part of the Spotify API isn't implemented yet.

See:
https://github.com/librespot-org/librespot/issues/1127

And also related I believe:
https://github.com/librespot-org/librespot/issues/913
