### ISSUE TITLE
approx 10-15s delay 

### ISSUE THREAD

**Issue by Blackspell01** [dtcooper/raspotify#619]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Hey, first of all thank you for the great work!
My question would be wether a 10 second delay from playing a song till it actually starts is normal?
This topic (https://github.com/dtcooper/raspotify/issues/103) which was closed due to inactivity, dealt with this issue but the problem wasn't solved.
Maybe there is a tweak to reduce the latency or its just a general thing I have to accept.
By the way, download speed of the pi are 50mbits down and 10mbits up. Not overwhelmingly great but should suffice shouldn't it?
Thanks in advance!

**Comment by JasonLG1979** [comment]
I don't know what to tell you? I can't make your internet speed faster?

**Comment by Blackspell01** [comment]
The internet speed isn't the problem?

**Comment by JasonLG1979** [comment]
Do the logs say anything? When you run librespot in debug mode what does it say?

**Comment by Blackspell01** [comment]
Apr 06 13:51:23 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z INFO  librespot] librespot 0.4.2 9a92196 (Built on 2023-04-02, Build ID: oQtbI6jK, Profile: release)
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot] Environment variable(s):
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_NAME="Simons Raspberry Pi"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_BACKEND="alsa"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_CACHE="/var/cache/raspotify"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_SYSTEM_CACHE="/var/lib/raspotify"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_VERBOSE="1"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_BITRATE="160"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_CACHE_SIZE_LIMIT="1G"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_DEVICE="default"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot]                 LIBRESPOT_VOLUME_CTRL="linear"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z TRACE librespot] Using cached credentials.
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_discovery::server] Zeroconf server listening on 0.0.0.0:46699
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_discovery::server] Shutting down discovery server
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:4070
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:443
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:4070"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z INFO  librespot_core::session] Authenticated as "nervensäge44" !
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_core::session] new Session[0]
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Linear
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_connect::spirc] new Spirc[0]
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_connect::spirc] canonical_username: nervensäge44
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot::component] new MercuryManager
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_playback::mixer::mappings] Input volume 25373 mapped to: 38.72%
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_playback::player] new Player[0]
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z INFO  librespot_playback::audio_backend::alsa] Using AlsaSink with format: S16
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_playback::player] command=AddEventSender
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_playback::player] command=VolumeSet(25373)
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_core::session] Session[0] strong=3 weak=2
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z INFO  librespot_core::session] Country: "DE"
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_core::mercury] subscribed uri=hm://remote/user/nervens%C3%A4ge44/ count=0
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_connect::spirc] kMessageTypeNotify "FireTV 4K Wohnzimmer" 05d0272c5c24aa56f9da626eabad661e60ca75b0 1449672607 1680781884561 kPlayStatusStop
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_connect::spirc] kMessageTypeNotify "Mac mini von Simon" d8cd854dd6543d713e6d197b6857ab6392704f9f 1449672607 1680781884561 kPlayStatusStop
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_connect::spirc] kMessageTypeNotify "VSX-830 B0245D" 3846a059dce7272d5f25608de1721c668d4b7c22 1449672607 1680781884561 kPlayStatusStop
Apr 06 13:51:24 raspberrypi librespot[4504]: [2023-04-06T11:51:24Z DEBUG librespot_connect::spirc] kMessageTypeNotify "Simons FireTV 4k" 123345879b0dfeb969253cfaf4bd91f3de5a5a36 1449672607 1680781884561 kPlayStatusStop
Apr 06 13:51:29 raspberrypi librespot[4504]: [2023-04-06T11:51:29Z DEBUG librespot_connect::spirc] kMessageTypeNotify "Mac mini von Simon" d8cd854dd6543d713e6d197b6857ab6392704f9f 1449677754 1680781889708 kPlayStatusPlay
Apr 06 13:51:29 raspberrypi librespot[4504]: [2023-04-06T11:51:29Z DEBUG librespot_connect::spirc] kMessageTypeNotify "Mac mini von Simon" d8cd854dd6543d713e6d197b6857ab6392704f9f 1449677796 1680781889750 kPlayStatusPlay
Apr 06 13:51:32 raspberrypi librespot[4504]: [2023-04-06T11:51:32Z DEBUG librespot_connect::spirc] kMessageTypeNotify "Mac mini von Simon" d8cd854dd6543d713e6d197b6857ab6392704f9f 1449680390 1680781892344 kPlayStatusPlay
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_connect::spirc] kMessageTypeLoad "Mac mini von Simon" d8cd854dd6543d713e6d197b6857ab6392704f9f 1449685639 1680781892344 kPlayStatusPlay
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:user:nervens%C3%A4ge44:collection" index: 1 position_ms: 7978 status: kPlayStatusPlay position_measured_at: 1680781897684>
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_connect::spirc] Frame has 82 tracks
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_playback::player] command=SetAutoNormaliseAsAlbum(false)
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 132172875644644586369062906164063544849, audio_type: Track }, true, 7978)
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z INFO  librespot_playback::player] Loading <Umbrella (with 21 Savage & Young Nudy)> with Spotify URI <spotify:track:2Yt4SXIgmoaPZHGdRafp4P>
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_audio::fetch] Downloading file 90c0267c90fce31d887c42f6f2466f35e12b2463
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot::component] new ChannelManager
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_core::mercury] unknown subscription uri=social-connect/v2/session_update
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot_core::mercury] unknown subscription uri=social-connect/v2/session_update
Apr 06 13:51:37 raspberrypi librespot[4504]: [2023-04-06T11:51:37Z DEBUG librespot::component] new AudioKeyManager
Apr 06 13:51:38 raspberrypi librespot[4504]: [2023-04-06T11:51:38Z INFO  librespot_playback::player] <Umbrella (with 21 Savage & Young Nudy)> (222000 ms) loaded
Apr 06 13:51:38 raspberrypi librespot[4504]: [2023-04-06T11:51:38Z TRACE librespot_playback::player] == Starting sink ==
Apr 06 13:51:38 raspberrypi librespot[4504]: [2023-04-06T11:51:38Z TRACE librespot_playback::audio_backend::alsa] Supported Period Range in Frames: 444..=32768
Apr 06 13:51:46 raspberrypi librespot[4504]: [2023-04-06T11:51:46Z DEBUG librespot_audio::fetch] File 90c0267c90fce31d887c42f6f2466f35e12b2463 complete, saving to cache
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] Closest Supported Period Size to Optimal (4410): 4408
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] Error getting Buffer Size, Min Buffer Size must be at least twice the Period Size
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] Falling back to the device's defaults
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] A Buffer Size of 32768 Frames is Suboptimal
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] A larger than necessary Buffer Size can lead to perceivable latency (lag).
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] A Period Size of 444 Frames is Suboptimal
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] A smaller than necessary Period Size relative to Buffer Size can lead to high CPU usage.
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_playback::audio_backend::alsa] Period Buffer size in bytes: 1776
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:51:48 raspberrypi librespot[4504]: [2023-04-06T11:51:48Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
Apr 06 13:51:54 raspberrypi librespot[4504]: [2023-04-06T11:51:54Z DEBUG librespot_connect::spirc] kMessageTypeLoad "Mac mini von Simon" d8cd854dd6543d713e6d197b6857ab6392704f9f 1449701525 1680781908859 kPlayStatusPlay
Apr 06 13:51:54 raspberrypi librespot[4504]: [2023-04-06T11:51:54Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:user:nervens%C3%A4ge44:collection" index: 8 position_ms: 0 status: kPlayStatusPlay position_measured_at: 0 context_descri>
Apr 06 13:51:54 raspberrypi librespot[4504]: [2023-04-06T11:51:54Z DEBUG librespot_connect::spirc] Frame has 89 tracks
Apr 06 13:51:54 raspberrypi librespot[4504]: [2023-04-06T11:51:54Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:51:54 raspberrypi librespot[4504]: [2023-04-06T11:51:54Z DEBUG librespot_playback::player] command=SetAutoNormaliseAsAlbum(false)
Apr 06 13:51:54 raspberrypi librespot[4504]: [2023-04-06T11:51:54Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 67249403840787176181377417666360045577, audio_type: Track }, true, 0)
Apr 06 13:51:54 raspberrypi librespot[4504]: [2023-04-06T11:51:54Z TRACE librespot_playback::player] == Stopping sink ==
Apr 06 13:51:55 raspberrypi librespot[4504]: [2023-04-06T11:51:55Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:51:55 raspberrypi librespot[4504]: [2023-04-06T11:51:55Z INFO  librespot_playback::player] Loading <Dream On> with Spotify URI <spotify:track:1xsYj84j7hUDDnTTerGWlH>
Apr 06 13:51:55 raspberrypi librespot[4504]: [2023-04-06T11:51:55Z DEBUG librespot_audio::fetch] File e8166d5177fd491d32d3316f09b1e33366501e28 already in cache
Apr 06 13:51:55 raspberrypi librespot[4504]: [2023-04-06T11:51:55Z INFO  librespot_playback::player] <Dream On> (267596 ms) loaded
Apr 06 13:51:55 raspberrypi librespot[4504]: [2023-04-06T11:51:55Z TRACE librespot_playback::player] == Starting sink ==
Apr 06 13:51:55 raspberrypi librespot[4504]: [2023-04-06T11:51:55Z TRACE librespot_playback::audio_backend::alsa] Supported Period Range in Frames: 444..=32768
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] Closest Supported Period Size to Optimal (4410): 4408
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] Error getting Buffer Size, Min Buffer Size must be at least twice the Period Size
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] Falling back to the device's defaults
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] A Buffer Size of 32768 Frames is Suboptimal
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] A larger than necessary Buffer Size can lead to perceivable latency (lag).
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] A Period Size of 444 Frames is Suboptimal
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] A smaller than necessary Period Size relative to Buffer Size can lead to high CPU usage.
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_playback::audio_backend::alsa] Period Buffer size in bytes: 1776
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:52:05 raspberrypi librespot[4504]: [2023-04-06T11:52:05Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z DEBUG librespot_connect::spirc] kMessageTypeLoad "Mac mini von Simon" d8cd854dd6543d713e6d197b6857ab6392704f9f 1449717280 1680781925208 kPlayStatusPlay
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:user:nervens%C3%A4ge44:collection" index: 5 position_ms: 0 status: kPlayStatusPlay position_measured_at: 0 context_descri>
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z DEBUG librespot_connect::spirc] Frame has 86 tracks
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z DEBUG librespot_playback::player] command=SetAutoNormaliseAsAlbum(false)
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 193176553073303077620002332618978725934, audio_type: Track }, true, 0)
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z TRACE librespot_playback::player] == Stopping sink ==
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z INFO  librespot_playback::player] Loading <Stop It> with Spotify URI <spotify:track:4qetR2UUyBeUrJ9DbYrpVQ>
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z DEBUG librespot_audio::fetch] File 7305b032de88fc22380898ad2042aa104b7d49bb already in cache
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z INFO  librespot_playback::player] <Stop It> (163790 ms) loaded
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z TRACE librespot_playback::player] == Starting sink ==
Apr 06 13:52:10 raspberrypi librespot[4504]: [2023-04-06T11:52:10Z TRACE librespot_playback::audio_backend::alsa] Supported Period Range in Frames: 444..=32768
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] Closest Supported Period Size to Optimal (4410): 4408
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] Error getting Buffer Size, Min Buffer Size must be at least twice the Period Size
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] Falling back to the device's defaults
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] A Buffer Size of 32768 Frames is Suboptimal
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] A larger than necessary Buffer Size can lead to perceivable latency (lag).
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] A Period Size of 444 Frames is Suboptimal
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] A smaller than necessary Period Size relative to Buffer Size can lead to high CPU usage.
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_playback::audio_backend::alsa] Period Buffer size in bytes: 1776
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Apr 06 13:52:20 raspberrypi librespot[4504]: [2023-04-06T11:52:20Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay


Is this the specific log you have requested?

**Comment by JasonLG1979** [comment]
That works out to about a 0.74 sec buffer size which is not horrible. So you looking at less than a sec of audio latency. So your issue is network latency somewhere.

**Comment by JasonLG1979** [comment]
The currently librespot does not use a CDN so who knows from where the song is downloaded for playback or how long it will take for commands to be issued. That's really on Spotify. The newer API being worked on in the dev branch is planning on using a CDN so there should be much less latency.

**Comment by Blackspell01** [comment]
Hmm ok.
But you can see that from starting sink (13:52:10) to kPlayStatusPlay (13:52:20) there's a 10 second gap in between.
How could I check if there's a network latency issue? 
And the "Error getting Buffer Size, Min Buffer Size must be at least twice the Period Size" is nothing to worry about?

**Comment by JasonLG1979** [comment]
The buffer message is just the result of a sanity check failing. It's not good but it's not the end of the world. Basically if that fails the backend will use the device's defaults whatever they may be.

**Comment by JasonLG1979** [comment]
The network delay is the issue. I would start by pinging the device you're connected to and then try to ping the AP you're connected to.

**Comment by Blackspell01** [comment]
<img width="1258" alt="Screenshot 2023-04-06 at 16 53 38" src="https://user-images.githubusercontent.com/65290701/230417442-1f7929b6-56f1-4e97-b96f-13f40b5d204b.png">

Ok but everything seems to be quite normal actually

**Comment by JasonLG1979** [comment]
Ping the AP.

**Comment by Blackspell01** [comment]
Im sorry what is the AP ?

**Comment by JasonLG1979** [comment]
ap-gew1.spotify.com in your case it's in the logs. I'm not sure if it respond to the ping or not though?

**Comment by Blackspell01** [comment]
<img width="887" alt="Screenshot 2023-04-06 at 18 07 14" src="https://user-images.githubusercontent.com/65290701/230435574-5d4a272e-a6a6-422c-a766-391a0be65d0a.png">

yes it does

**Comment by JasonLG1979** [comment]
Very strange. Those are very good numbers too? I'm kinda at a loss here.

**Comment by Blackspell01** [comment]
Unfortunate, anyways thank you for your help!

**Comment by JasonLG1979** [comment]
No problem. With luck it's just something on Spotify's side and it clears itself up in a couple day?

**Comment by Blackspell01** [comment]
Hey I just wanted to let you know that I fixed the issue by installing pulse audio instead of ALSA. Now it works flawlessly!
Thank you

**Comment by JasonLG1979** [comment]
> Hey I just wanted to let you know that I fixed the issue by installing pulse audio instead of ALSA. Now it works flawlessly!
> Thank you

Weird. You still have ALSA. PulseAudio sits on top ALSA, you can't not have ALSA. I'm very surprised that it would have any noticeable affect at all as far as latency?

**Comment by JasonLG1979** [comment]
If anything PulseAudio should add additional audio latency.
