### ISSUE TITLE
Raspotify, Music History

### ISSUE THREAD

**Issue by TruePcKing** [dtcooper/raspotify#635]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Not sure if this has been noticed before, and this is probably more of a Spotify issue, but music played from the Raspotify aren't categorized under my playlist. 

You can view music history on the mobile app
![Spotify Music History](https://github.com/dtcooper/raspotify/assets/78933694/3a9dc1cb-21f9-4b23-8e2a-0a38bbdd4636)

**Comment by JasonLG1979** [comment]
That is a know issue with librespot.

**Comment by JasonLG1979** [comment]
It's related to this:

https://github.com/librespot-org/librespot/issues/1127

Librespot doesn't report back to Spotify that it's playing or has player a track.
