### ISSUE TITLE
Bluetooth Pulseaudio raspotify.service up to date?

### ISSUE THREAD

**Issue by bruvv** [dtcooper/raspotify#639]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

When reading: https://github.com/dtcooper/raspotify/wiki/Play-via-Bluetooth-Speaker I noticed that the raspotify.service is very different then the current one in the repo, is this wiki one still the way to go when using pulseaudio? For some reason I can get my bluetooth speaker to work with pulseaudio and not with bluealsa (not running gui btw, 32 bit lite OS on a pi 4B)

**Comment by JasonLG1979** [comment]
Bluetooth is a roll your own use case. It's not supported by me. It's up to you or other users to figure it out and if/when you do you can fix the wiki.
