### ISSUE TITLE
service not found

### ISSUE THREAD

**Issue by sgarro** [dtcooper/raspotify#64]
I have raspotify installed, in fact if i try again to apt-get i got "raspotify is already the newest version (0.9.1~librespot.20171005T125424Z.8971d3a)."

But i can't find the service  anywhere.
is listed in systemc list-unit-files as enabled. i have the configuration file. but when i try to launch it, systemctl is unabled to locate it and it gives me 
Failed to get properties: No such interface ''

**Comment by fossedihelm** [comment]
Making a search I found that the problem probably is not related to raspotify but to upstart that prevent .service files to be started. Look more here. https://askubuntu.com/questions/894419/systemd-on-ubuntu-16-04-gives-no-such-interface-error
