### ISSUE TITLE
Sleep timer

### ISSUE THREAD

**Issue by boresk** [dtcooper/raspotify#647]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Is there a way to get the sleep timer? There's a sleep timer (stop music after x minutes) on spotify, but this option is not available when selecting the raspotify device. Is there a way to do something similar?

**Comment by janek** [comment]
I'm not the maintainer, but I think this might be outside the scope of what this project does/is meant to do. To achieve this, you could write your own program that triggers the "pause" endpoint of the Spotify API. I have an alarm clock project that uses raspotify to do the reverse of this (start at a certain time). I use crontab to schedule it. You can see the code here: https://github.com/janek/music-alarm-clock.

If you want the easiest/quickest way to do this, it could be worth trying to do it with make.com - depends on how you imagine triggering the pause (what interface/device you'd like to use for it). If you use code you have to manage authorizing Spotify yourself, which also means creating a an account as a Spotify Developer, etc.
