### ISSUE TITLE
Can't reinstall Raspotify (see inside for error message)

### ISSUE THREAD

**Issue by heinzgruber** [dtcooper/raspotify#650]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Hi,
my Raspotify installation was broken and i've had no idea why. My clients can't connect anymore the my Raspberry Pi Zero 2. Since multiple reboots didn't help i uninstalled Rapsotify via 

sudo apt-get remove -y raspotify

and deleted the rapsotify folder in /etc

when i try to reinstall via 

sudo apt-get -y install curl && curl -sL https://dtcooper.github.io/raspotify/install.sh | sh

nothing happens and i get this output:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.74.0-1.3+deb11u11).
The following packages were automatically installed and are no longer required:
  libasyncns0 libopus0 libpulse0 libsndfile1 libvorbisenc2 raspinfo
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I'm using Raspberry Pi OS Lite 11 Bullseye 64 Bit

What am i doing wrong?

Thanks

**Comment by mquevill** [comment]
When I tried to replicate your steps, the new `/etc/raspotify` directory seemed to have restrictive permissions:
```
drw-------   2 root root    4096 May  1 15:25 raspotify
```
and
```
-rw-------   1 root root  5015 Jun 21  2023 conf
```
Furthermore, I then get issues listed in `sudo journalctl -u raspotify -b` that specify `librespot: Failed to get home directory.`

This is with a Raspberry Pi OS Desktop 12 on a Raspberry Pi 2 (32 bit). This definitely seems like strange behavior on a reinstall.

**Comment by mquevill** [comment]
I retried this process with a fresh install of Raspberry Pi OS Lite 12, and it was able to reinstall properly. The permissions are how the files appear even on first install; they just seem a bit restrictive compared to other directories.

@heinzgruber You may need to debug the install.sh script on your machine to pinpoint where it's going wrong. The script is set up to have error checking + error messages, but it's hard to tell what's happening with the limited output you included.
