### ISSUE TITLE
Can't here sound from audio hat( raspberry pi 4b + Adafruit Voice Bonnet)

### ISSUE THREAD

**Issue by thenukaperea** [dtcooper/raspotify#668]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Im using raspberry pi 4b + Adafruit Voice Bonnet, and i followed the steps as given in the site (https://learn.adafruit.com/adafruit-voice-bonnet/blinka-setup) I got the results as mentioned in the guide lines, but I can't here anything. installed 64 bit bookworm OS
![Screenshot 2024-09-03 at 14 19 52](https://github.com/user-attachments/assets/0e8ab8ae-7030-4d5d-b68b-ca21f1ca20f0)

**Comment by kimtore** [comment]
Too bad your audio is not working, but I don't see how Raspotify has anything to do with Adafruit Voice Bonnet?

**Comment by kimtore** [comment]
Might also be related to #676
