### ISSUE TITLE
Volume low at 100%

### ISSUE THREAD

**Issue by MrJoki007** [dtcooper/raspotify#67]
Before i used Spotify Connect Web but that does not work anymore in Debian stretch.
Now i upgraded to Raspotify but the Problem i have is that max Volume on Spotify Connect Web was very loud but now when i turn it to max its like a quarter of the old volume.

**Comment by dalori** [comment]
This is not an issue concerning the repo, is it? I suggest to add a remark into the readme to use e.g. `alsamixer` in the command line to increase the volume of the Raspberry Pi.

**Comment by MrJoki007** [comment]
Oh yes that was the problem.
Ive seen alot of users who had this problem

**Comment by dtcooper** [comment]
Duly noted. Thanks for helping @MrJoki007, @dalori. I'll create a Troubleshooting section to the Readme and add this there. :)
