### ISSUE TITLE
Upgrade Raspotify

### ISSUE THREAD

**Issue by Kybeer** [dtcooper/raspotify#677]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

Hello,

What is the best way to upgrade Raspotify? Backup the main config file (/etc/raspotify/conf) and simply download/reinstall?

**Comment by kimtore** [comment]
If you added the Raspotify repository to your deb sources, it should be as simple as:
`apt-get update && apt-get install raspotify` (or `apt-get upgrade`)
Otherwise, a download + reinstall is also sufficient.
