### ISSUE TITLE
Connection timed out (os error 110)

### ISSUE THREAD

**Issue by Napoletana** [dtcooper/raspotify#679]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

I'm getting an error on raspotify after a long overdue update cycle: 

0:00: Started Raspotify (Spotify Connect Client).
2:20: librespot[5021]: [2024-10-12T18:13:48Z ERROR librespot] could not initialize spirc: Deadline expired before operation could complete { Connection timed out (os error 110) }

after which:
systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE

I've tried manually running librespot, but that didn't work either with the same error. 
I've tried purging and reinstalling raspotify
I've tried adjusting the DNS in pihole to connect to a different spotify AP
Manually added credentials to the configuration didn't work either. 

The only posts with error 110 that I can see were 'magically' fixed...

**Comment by kimtore** [comment]
> I've tried manually running librespot, but that didn't work either with the same error.

Then it is probably not a Raspotify error, because Raspotify is only a wrapper around librespot. So probably best to ask librespot devs, because I really don't know about your error.

Also, not sure what you're referring to about magically fixed error 110?

Try not using your PiHole and see if that helps.

**Comment by kimtore** [comment]
Perhaps you'd like to try the 0.45.0 release which contains librespot 0.5.0 with many bug fixes.

**Comment by Napoletana** [comment]
I can confirm, the update (0.44.1 --> 0.45.0) fixed the issue. Thanks a lot!
