### ISSUE TITLE
significantly quieter then Moode with the same DAC

### ISSUE THREAD

**Issue by dwhacks** [dtcooper/raspotify#687]
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Are you sure?

- [X] I'm not trying to run Raspotify on a ARMv6 device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Compatible Configuration

- [X] I'm running Raspotify on a compatible Configuration

### Latest Version

- [X] I'm running the latest version of Raspotify

### Are you sure?

- [X] I'm not running Raspotify 0.31.8.1 on a Pi v1 or Pi Zero

### Due Diligence

- [X] I have done my due diligence

### What happened?

I use Moodeaudio for my main system with a Raspberry pi 3 and a ProtoDac. I had enough extra parts so I figured I would setup a simple wifi only system with another ProtoDac and Raspotify running on a Zero 2 W. 

I installed a fresh lite OS (64), updated the system and then used the install script on this github. 

I enabled i2s in /boot/firmware/config.txt:

dtparam=i2s=on
/# Audio overlays
dtoverlay=i2s-dac

and when I run the command to find audio devices it seems to work and selects my ProtoDac as default:
` 
dwhacks@raspotify:~ $ sudo librespot -d ?
[2024-11-12T05:18:46Z INFO  librespot] librespot 0.5.0 84d28e8 (Built on 2024-10-17, Build ID: CmvEuO4M, Profile: release)

	Compatible alsa device(s):

	------------------------------------------------------

	Device:

		hw:CARD=sndrpirpidac,DEV=0

	Description:

		snd_rpi_rpi_dac, RPi-DAC HiFi pcm1794a-hifi-0
		Direct hardware device without any conversions

	Supported Format(s):

		S16 S24

	------------------------------------------------------

	Device:

		plughw:CARD=sndrpirpidac,DEV=0

	Description:

		snd_rpi_rpi_dac, RPi-DAC HiFi pcm1794a-hifi-0
		Hardware device with all software conversions

	Supported Format(s):

		S16 S24 S24_3 S32 F32 F64

	------------------------------------------------------

	Device:

		default:CARD=sndrpirpidac

	Description:

		snd_rpi_rpi_dac, RPi-DAC HiFi pcm1794a-hifi-0
		Default Audio Device

	Supported Format(s):

		S16 S24 S24_3 S32 F32 F64

	------------------------------------------------------

	Device:

		sysdefault:CARD=sndrpirpidac

	Description:

		snd_rpi_rpi_dac, RPi-DAC HiFi pcm1794a-hifi-0
		Default Audio Device

	Supported Format(s):

		S16 S24 S24_3 S32 F32 F64

	------------------------------------------------------

ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave 
`

I connected the finished device to my system and it is significantly quieter then my Moode device using the same DAC. I have read the "troubleshooting" and there is no option to change volume with alsamixer. I have set default volume to 100, removed normalization and even changed "log" to "fixed" with no change in output.

any ideas? 

Protodac info here: https://github.com/moode-player/protodac/blob/main/docs/protodac_tda1387_x8.md

### Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )

```shell
# Audio device to use, use `librespot --device ?` to list options.
# Defaults to the system's default.
#LIBRESPOT_DEVICE="default"

# Initial volume in % from 0 - 100.
# Defaults to 50 For the alsa mixer: the current volume.
LIBRESPOT_INITIAL_VOLUME="100"

# Volume control scale type {cubic|fixed|linear|log}.
# Defaults to log.
LIBRESPOT_VOLUME_CTRL="log"

# Range of the volume control (dB) from 0.0 to 100.0.
# Default for softvol: 60.0.
# For the alsa mixer: what the control supports.
LIBRESPOT_VOLUME_RANGE="100.0"
```

**Comment by kimtore** [comment]
Hi @dwhacks
Librespot's volume attenuation is applied before any ALSA volume settings, so if you want maximum volume you will want to set them to 100% both in alsamixer and Librespot.
Also, you might have better results by opting for hardware control directly, see https://github.com/librespot-org/librespot/wiki/Options:
```
LIBRESPOT_MIXER=alsa
LIBRESPOT_MIXER_CONTROL=<...>
```
