### ISSUE TITLE
A Few Issues

### ISSUE THREAD

**Issue by andy646362** [dtcooper/raspotify#71]
Hello there and thanks for this awesome raspi project!

After a few issues I got it working (USB sound card didn't work at first and only HDMI player sound, but [this thread solved it](https://github.com/dtcooper/raspotify/issues/22)) I am now listening to spotify through the raspberry. However, it still lacks a few functions:

(1) I can't like or dislike songs currently playing
(2) I can't turn on shuffle in a playlist (very annoying)
(3) If I start a radio station, new songs won't load. Just the first few
songs from that station will play on repeat.

Are there plans to adress these things in the future?

Thanks again!

**Comment by dtcooper** [comment]
Hi @andy646362, these are underlying issue with [librespot](https://github.com/librespot-org/librespot), so you may be better served filing the issues *with* steps to reproduce there. Thanks!
