### ISSUE TITLE
Possible to stream local files?

### ISSUE THREAD

**Issue by danielalvsaaker** [dtcooper/raspotify#72]
I know Spotify allows streaming local files between certain devices. Would it be possible to implement this feature for raspotify as well?

**Comment by BenjaminAlpert** [comment]
I agree. That would be a great feature to add! If possible, please implement.

**Comment by rlaferla** [comment]
PLEASE add support for local files!

**Comment by JasonLG1979** [comment]
No. Raspotify is just a packaged version of librespot. It does not implement any features.
