### ISSUE TITLE
raspotify on stretch

### ISSUE THREAD

**Issue by riker65** [dtcooper/raspotify#73]
Hi
is the jessie version running on stretch as well?

thanks

**Comment by markusradmark** [comment]
It works for me!

**Comment by riker65** [comment]
ok , thanks will try. will there be new sources available for stretch?

**Comment by markusradmark** [comment]
I used the jessie sources and it works

**Comment by riker65** [comment]
ok for me too

**Comment by dtcooper** [comment]
Note: I renamed the repository codename to `raspotify` since `jessie` was misleading in df5a09c9. (`jessie` will still work for backward compatibility).
