### ISSUE TITLE
Now playing on 16x2 LCD?

### ISSUE THREAD

**Issue by markusradmark** [dtcooper/raspotify#76]
Hi!
I'm really new to this but i got my RPi2 with hifiberry dac+ pro working.
Got some text on the 16x2 LCD with RPi.GPIO module but is it possible to get the track artist and titel?

**Comment by ClemaX** [comment]
You could edit the raspotify.service and pipe the librespot output to parse it with your python script.
If you combine this with a higher level of verbosity, you might be able to get everything you need.

**Comment by dtcooper** [comment]
What about adding an `--onchange /path.to/myscript.sh` that detects for change events, and looks up the track ID on the Spotify API? @markusradmark
