### ISSUE TITLE
Problem with making the connect visible over internet with spotify account through facebook

### ISSUE THREAD

**Issue by mxjelle** [dtcooper/raspotify#79]
Hey.

I cannot see the raspotify connect through Windows, only through mobile phones on same local network? Does that mean, that in order for making it work for windows control, it needs to be set up to be visible over the internet? 

I am having problems getting this visibility setup. I have my spotify account through facebook, i do not know if this is a problem, as it might not be seen as a "pure" spotify account? 

Hope someone can help, so i can get my project up and running.

**Comment by brunob45** [comment]
In order to have access to raspotify through Internet, you have to setup a device password, and use it to log in raspotify. You can setup this here : https://www.spotify.com/ca-en/account/set-device-password/
