### ISSUE TITLE
Non-linear volume levels

### ISSUE THREAD

**Issue by johan-andersson01** [dtcooper/raspotify#90]
When adjusting the volume from a client (tested on Spotify for Android and Linux), the volume increase/decrease is non-linear. 

Graphical volume bar (LEFT) vs actual approximate volume levels (RIGHT):

- 100%  : 100%
- 90% : 60%
- 75% :  20%
- 50% : 5%
- 25% : inaudible

Raspotify version: [4c41424](https://github.com/dtcooper/raspotify/commit/4c4142452fc0f090a4c1bfb1f92f5690e9a1805a)

**Comment by dtcooper** [comment]
So are you saying I should remove the `--enable-volume-normalisation` flag?

**Comment by johan-andersson01** [comment]
Is that the cause?

I definitely prefer normalized volumes over linear volume control, if I have to pick only one of them. But if it would be possible to have both, then that would be awesome. :smiley: 

Thanks for taking the time to develop this btw, it has really redefined my listening experience at home :heart:

**Comment by dtcooper** [comment]
> Thanks for taking the time to develop this btw, it has really redefined my listening experience at home ❤️

You're welcome! I'm not sure if that's the cause, that's just the change in the commit you sent me ([`4c41424`](https://github.com/dtcooper/raspotify/commit/4c4142452fc0f090a4c1bfb1f92f5690e9a1805a)). I'll try to repro this weekend and remove it if the volume is wonky for me.

**Comment by johan-andersson01** [comment]
Works perfectly. Thanks!
