### ISSUE TITLE
No sound first few seconds on new song?

### ISSUE THREAD

**Issue by hargibii** [dtcooper/raspotify#98]
As the title says. I dont get any sound for the first few seconds when changeing song.

Running a RPI3 with debian. Output is trough HDMI to an denon recever.

running the latest build from github.

**Comment by aalvarez737** [comment]
I'm getting the same issue, but it seems to be related to track loading. The sound starts when the log say track loaded (systemctl status).

**Comment by gabmartini** [comment]
Same here. Using Raspian Stretch and moodeAudio.

**Comment by hargibii** [comment]
any way to minimize this issue?

**Comment by MelBourbon** [comment]
I think as long as librespot does not support gapless playback ( https://github.com/librespot-org/librespot/issues/21) this can not be resolved since the next song needs to be preloaded.

**Comment by kennell** [comment]
Same issue here after recently reinstallting everything from scratch on a clean Raspbian installation. Did not have this issue previously.
